// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"monster/internal/biz"
	"monster/internal/conf"
	"monster/internal/data"
	"monster/internal/server"
	"monster/internal/service"
	"monster/pkg/payment"
	"monster/pkg/sms"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confAuth *conf.Auth, confSms *conf.Sms, confBusiness *conf.Business, confWeChat *conf.WeChat, confAlipay *conf.Alipay, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}

	redisClient := data.NewRedis(confData)

	smsClient := sms.NewIhuyiSender(confSms.APIID, confSms.APIKEY)

	dataData, cleanup, err := data.NewData(confData, db, redisClient, smsClient, logger)
	if err != nil {
		return nil, nil, err
	}

	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)

	walletRepo := data.NewWalletRepo(dataData, logger)
	walletUsecase := biz.NewWalletUsecase(walletRepo, logger)

	orderRepo := data.NewOrderRepo(dataData, logger)
	redisLock := data.NewRedisLock(redisClient)
	pricingConfig := pricingConfigProvider(confBusiness)
	orderUsecase := biz.NewOrderUsecase(orderRepo, walletRepo, redisLock, pricingConfig, logger)

	paymentRepo := data.NewPaymentRepo(dataData, logger)

	// Build payment channel manager
	var wechatNotifyURL, wechatAppID, wechatMchID, wechatAPIKey string
	if confWeChat != nil {
		wechatAppID = confWeChat.AppID
		wechatMchID = confWeChat.MchID
		wechatAPIKey = confWeChat.APIKey
		wechatNotifyURL = confWeChat.NotifyURL
	}
	var alipayAppID, alipayPrivate, alipayReturn, alipayNotify string
	if confAlipay != nil {
		alipayAppID = confAlipay.AppId
		alipayPrivate = confAlipay.Private
		alipayReturn = confAlipay.ReturnUrl
		alipayNotify = confAlipay.NotifyUrl
	}
	payManager, err := payment.NewIntegratedManager(wechatAppID, wechatMchID, wechatAPIKey, wechatNotifyURL, alipayAppID, alipayPrivate, alipayReturn, alipayNotify)
	if err != nil {
		return nil, nil, err
	}

	paymentUsecase := biz.NewPaymentUsecase(paymentRepo, payManager, orderRepo, walletRepo, logger)

	jwtObj := conf.NewJWT(confAuth)

	userService := service.NewUserService(userUsecase, walletUsecase, jwtObj, logger)
	orderService := service.NewOrderService(orderUsecase, logger)
	paymentService := service.NewPaymentService(paymentUsecase, logger)

	grpcServer := server.NewGRPCServer(confServer, userService, orderService, paymentService, logger)
	httpServer := server.NewHTTPServer(confServer, jwtObj, userService, orderService, paymentService, logger)

	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
