// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: order/v1/order.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Order_PreCheckBorrow_FullMethodName            = "/order.v1.Order/PreCheckBorrow"
	Order_CreateOrder_FullMethodName               = "/order.v1.Order/CreateOrder"
	Order_CancelOrder_FullMethodName               = "/order.v1.Order/CancelOrder"
	Order_ReturnPowerBank_FullMethodName           = "/order.v1.Order/ReturnPowerBank"
	Order_ExtendRental_FullMethodName              = "/order.v1.Order/ExtendRental"
	Order_GetCurrentOrder_FullMethodName           = "/order.v1.Order/GetCurrentOrder"
	Order_GetRealTimeFee_FullMethodName            = "/order.v1.Order/GetRealTimeFee"
	Order_ListOrders_FullMethodName                = "/order.v1.Order/ListOrders"
	Order_CreateCompensationPayment_FullMethodName = "/order.v1.Order/CreateCompensationPayment"
	Order_GetStation_FullMethodName                = "/order.v1.Order/GetStation"
	Order_ListNearbyStations_FullMethodName        = "/order.v1.Order/ListNearbyStations"
	Order_GetCabinetList_FullMethodName            = "/order.v1.Order/GetCabinetList"
	Order_GetOrderDetail_FullMethodName            = "/order.v1.Order/GetOrderDetail"
	Order_GetDelayFee_FullMethodName               = "/order.v1.Order/GetDelayFee"
	Order_ScanCabinet_FullMethodName               = "/order.v1.Order/ScanCabinet"
)

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 订单服务（充电宝租借全流程管理）
type OrderClient interface {
	// 租借前预检
	PreCheckBorrow(ctx context.Context, in *PreCheckBorrowRequest, opts ...grpc.CallOption) (*PreCheckBorrowResponse, error)
	// 创建租借订单
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	// 取消订单
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	// 归还充电宝
	ReturnPowerBank(ctx context.Context, in *ReturnPowerBankRequest, opts ...grpc.CallOption) (*ReturnPowerBankResponse, error)
	// 延长租借
	ExtendRental(ctx context.Context, in *ExtendRentalRequest, opts ...grpc.CallOption) (*ExtendRentalResponse, error)
	// 查询当前订单
	GetCurrentOrder(ctx context.Context, in *GetCurrentOrderRequest, opts ...grpc.CallOption) (*GetCurrentOrderResponse, error)
	// 实时费用查询
	GetRealTimeFee(ctx context.Context, in *GetRealTimeFeeRequest, opts ...grpc.CallOption) (*GetRealTimeFeeResponse, error)
	// 历史订单查询
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
	// 待赔付支付入口
	CreateCompensationPayment(ctx context.Context, in *CreateCompensationPaymentRequest, opts ...grpc.CallOption) (*CreateCompensationPaymentResponse, error)
	// 获取站点详情
	GetStation(ctx context.Context, in *GetStationRequest, opts ...grpc.CallOption) (*GetStationResponse, error)
	// 查询附近站点（含距离和空闲充电宝数）
	ListNearbyStations(ctx context.Context, in *ListNearbyStationsRequest, opts ...grpc.CallOption) (*ListNearbyStationsResponse, error)
	// 查询站点下所有机柜及仓位详情
	GetCabinetList(ctx context.Context, in *GetCabinetListRequest, opts ...grpc.CallOption) (*GetCabinetListResponse, error)
	// 查询订单详情（含借还机柜仓位信息）
	GetOrderDetail(ctx context.Context, in *GetOrderDetailRequest, opts ...grpc.CallOption) (*GetOrderDetailResponse, error)
	// 延长租借费用预览
	GetDelayFee(ctx context.Context, in *GetDelayFeeRequest, opts ...grpc.CallOption) (*GetDelayFeeResponse, error)
	// 扫码解析机柜（扫描二维码进入机柜详情）
	ScanCabinet(ctx context.Context, in *ScanCabinetRequest, opts ...grpc.CallOption) (*ScanCabinetResponse, error)
}

type orderClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderClient(cc grpc.ClientConnInterface) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) PreCheckBorrow(ctx context.Context, in *PreCheckBorrowRequest, opts ...grpc.CallOption) (*PreCheckBorrowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreCheckBorrowResponse)
	err := c.cc.Invoke(ctx, Order_PreCheckBorrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, Order_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, Order_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) ReturnPowerBank(ctx context.Context, in *ReturnPowerBankRequest, opts ...grpc.CallOption) (*ReturnPowerBankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReturnPowerBankResponse)
	err := c.cc.Invoke(ctx, Order_ReturnPowerBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) ExtendRental(ctx context.Context, in *ExtendRentalRequest, opts ...grpc.CallOption) (*ExtendRentalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtendRentalResponse)
	err := c.cc.Invoke(ctx, Order_ExtendRental_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetCurrentOrder(ctx context.Context, in *GetCurrentOrderRequest, opts ...grpc.CallOption) (*GetCurrentOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentOrderResponse)
	err := c.cc.Invoke(ctx, Order_GetCurrentOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetRealTimeFee(ctx context.Context, in *GetRealTimeFeeRequest, opts ...grpc.CallOption) (*GetRealTimeFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRealTimeFeeResponse)
	err := c.cc.Invoke(ctx, Order_GetRealTimeFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrdersResponse)
	err := c.cc.Invoke(ctx, Order_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateCompensationPayment(ctx context.Context, in *CreateCompensationPaymentRequest, opts ...grpc.CallOption) (*CreateCompensationPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCompensationPaymentResponse)
	err := c.cc.Invoke(ctx, Order_CreateCompensationPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetStation(ctx context.Context, in *GetStationRequest, opts ...grpc.CallOption) (*GetStationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStationResponse)
	err := c.cc.Invoke(ctx, Order_GetStation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) ListNearbyStations(ctx context.Context, in *ListNearbyStationsRequest, opts ...grpc.CallOption) (*ListNearbyStationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNearbyStationsResponse)
	err := c.cc.Invoke(ctx, Order_ListNearbyStations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetCabinetList(ctx context.Context, in *GetCabinetListRequest, opts ...grpc.CallOption) (*GetCabinetListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCabinetListResponse)
	err := c.cc.Invoke(ctx, Order_GetCabinetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetOrderDetail(ctx context.Context, in *GetOrderDetailRequest, opts ...grpc.CallOption) (*GetOrderDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderDetailResponse)
	err := c.cc.Invoke(ctx, Order_GetOrderDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetDelayFee(ctx context.Context, in *GetDelayFeeRequest, opts ...grpc.CallOption) (*GetDelayFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDelayFeeResponse)
	err := c.cc.Invoke(ctx, Order_GetDelayFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) ScanCabinet(ctx context.Context, in *ScanCabinetRequest, opts ...grpc.CallOption) (*ScanCabinetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanCabinetResponse)
	err := c.cc.Invoke(ctx, Order_ScanCabinet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
// All implementations must embed UnimplementedOrderServer
// for forward compatibility.
//
// 订单服务（充电宝租借全流程管理）
type OrderServer interface {
	// 租借前预检
	PreCheckBorrow(context.Context, *PreCheckBorrowRequest) (*PreCheckBorrowResponse, error)
	// 创建租借订单
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	// 取消订单
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	// 归还充电宝
	ReturnPowerBank(context.Context, *ReturnPowerBankRequest) (*ReturnPowerBankResponse, error)
	// 延长租借
	ExtendRental(context.Context, *ExtendRentalRequest) (*ExtendRentalResponse, error)
	// 查询当前订单
	GetCurrentOrder(context.Context, *GetCurrentOrderRequest) (*GetCurrentOrderResponse, error)
	// 实时费用查询
	GetRealTimeFee(context.Context, *GetRealTimeFeeRequest) (*GetRealTimeFeeResponse, error)
	// 历史订单查询
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
	// 待赔付支付入口
	CreateCompensationPayment(context.Context, *CreateCompensationPaymentRequest) (*CreateCompensationPaymentResponse, error)
	// 获取站点详情
	GetStation(context.Context, *GetStationRequest) (*GetStationResponse, error)
	// 查询附近站点（含距离和空闲充电宝数）
	ListNearbyStations(context.Context, *ListNearbyStationsRequest) (*ListNearbyStationsResponse, error)
	// 查询站点下所有机柜及仓位详情
	GetCabinetList(context.Context, *GetCabinetListRequest) (*GetCabinetListResponse, error)
	// 查询订单详情（含借还机柜仓位信息）
	GetOrderDetail(context.Context, *GetOrderDetailRequest) (*GetOrderDetailResponse, error)
	// 延长租借费用预览
	GetDelayFee(context.Context, *GetDelayFeeRequest) (*GetDelayFeeResponse, error)
	// 扫码解析机柜（扫描二维码进入机柜详情）
	ScanCabinet(context.Context, *ScanCabinetRequest) (*ScanCabinetResponse, error)
	mustEmbedUnimplementedOrderServer()
}

// UnimplementedOrderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServer struct{}

func (UnimplementedOrderServer) PreCheckBorrow(context.Context, *PreCheckBorrowRequest) (*PreCheckBorrowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreCheckBorrow not implemented")
}
func (UnimplementedOrderServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedOrderServer) ReturnPowerBank(context.Context, *ReturnPowerBankRequest) (*ReturnPowerBankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReturnPowerBank not implemented")
}
func (UnimplementedOrderServer) ExtendRental(context.Context, *ExtendRentalRequest) (*ExtendRentalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtendRental not implemented")
}
func (UnimplementedOrderServer) GetCurrentOrder(context.Context, *GetCurrentOrderRequest) (*GetCurrentOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentOrder not implemented")
}
func (UnimplementedOrderServer) GetRealTimeFee(context.Context, *GetRealTimeFeeRequest) (*GetRealTimeFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRealTimeFee not implemented")
}
func (UnimplementedOrderServer) ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedOrderServer) CreateCompensationPayment(context.Context, *CreateCompensationPaymentRequest) (*CreateCompensationPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCompensationPayment not implemented")
}
func (UnimplementedOrderServer) GetStation(context.Context, *GetStationRequest) (*GetStationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStation not implemented")
}
func (UnimplementedOrderServer) ListNearbyStations(context.Context, *ListNearbyStationsRequest) (*ListNearbyStationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNearbyStations not implemented")
}
func (UnimplementedOrderServer) GetCabinetList(context.Context, *GetCabinetListRequest) (*GetCabinetListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCabinetList not implemented")
}
func (UnimplementedOrderServer) GetOrderDetail(context.Context, *GetOrderDetailRequest) (*GetOrderDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderDetail not implemented")
}
func (UnimplementedOrderServer) GetDelayFee(context.Context, *GetDelayFeeRequest) (*GetDelayFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDelayFee not implemented")
}
func (UnimplementedOrderServer) ScanCabinet(context.Context, *ScanCabinetRequest) (*ScanCabinetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanCabinet not implemented")
}
func (UnimplementedOrderServer) mustEmbedUnimplementedOrderServer() {}
func (UnimplementedOrderServer) testEmbeddedByValue()               {}

// UnsafeOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServer will
// result in compilation errors.
type UnsafeOrderServer interface {
	mustEmbedUnimplementedOrderServer()
}

func RegisterOrderServer(s grpc.ServiceRegistrar, srv OrderServer) {
	// If the following call panics, it indicates UnimplementedOrderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Order_ServiceDesc, srv)
}

func _Order_PreCheckBorrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreCheckBorrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).PreCheckBorrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_PreCheckBorrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).PreCheckBorrow(ctx, req.(*PreCheckBorrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_ReturnPowerBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnPowerBankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).ReturnPowerBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_ReturnPowerBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).ReturnPowerBank(ctx, req.(*ReturnPowerBankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_ExtendRental_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendRentalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).ExtendRental(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_ExtendRental_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).ExtendRental(ctx, req.(*ExtendRentalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetCurrentOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetCurrentOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_GetCurrentOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetCurrentOrder(ctx, req.(*GetCurrentOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetRealTimeFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRealTimeFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetRealTimeFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_GetRealTimeFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetRealTimeFee(ctx, req.(*GetRealTimeFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).ListOrders(ctx, req.(*ListOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateCompensationPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompensationPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateCompensationPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CreateCompensationPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateCompensationPayment(ctx, req.(*CreateCompensationPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_GetStation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetStation(ctx, req.(*GetStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_ListNearbyStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNearbyStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).ListNearbyStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_ListNearbyStations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).ListNearbyStations(ctx, req.(*ListNearbyStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetCabinetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCabinetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetCabinetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_GetCabinetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetCabinetList(ctx, req.(*GetCabinetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetOrderDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetOrderDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_GetOrderDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetOrderDetail(ctx, req.(*GetOrderDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetDelayFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelayFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetDelayFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_GetDelayFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetDelayFee(ctx, req.(*GetDelayFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_ScanCabinet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanCabinetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).ScanCabinet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_ScanCabinet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).ScanCabinet(ctx, req.(*ScanCabinetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Order_ServiceDesc is the grpc.ServiceDesc for Order service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Order_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.v1.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreCheckBorrow",
			Handler:    _Order_PreCheckBorrow_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Order_CreateOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Order_CancelOrder_Handler,
		},
		{
			MethodName: "ReturnPowerBank",
			Handler:    _Order_ReturnPowerBank_Handler,
		},
		{
			MethodName: "ExtendRental",
			Handler:    _Order_ExtendRental_Handler,
		},
		{
			MethodName: "GetCurrentOrder",
			Handler:    _Order_GetCurrentOrder_Handler,
		},
		{
			MethodName: "GetRealTimeFee",
			Handler:    _Order_GetRealTimeFee_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _Order_ListOrders_Handler,
		},
		{
			MethodName: "CreateCompensationPayment",
			Handler:    _Order_CreateCompensationPayment_Handler,
		},
		{
			MethodName: "GetStation",
			Handler:    _Order_GetStation_Handler,
		},
		{
			MethodName: "ListNearbyStations",
			Handler:    _Order_ListNearbyStations_Handler,
		},
		{
			MethodName: "GetCabinetList",
			Handler:    _Order_GetCabinetList_Handler,
		},
		{
			MethodName: "GetOrderDetail",
			Handler:    _Order_GetOrderDetail_Handler,
		},
		{
			MethodName: "GetDelayFee",
			Handler:    _Order_GetDelayFee_Handler,
		},
		{
			MethodName: "ScanCabinet",
			Handler:    _Order_ScanCabinet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/v1/order.proto",
}
