// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: order/v1/order.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreCheckBorrowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PowerBankId   int64                  `protobuf:"varint,1,opt,name=power_bank_id,json=powerBankId,proto3" json:"power_bank_id,omitempty"` // 充电宝ID
	StationId     int64                  `protobuf:"varint,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`         // 站点ID
	CabinetId     int64                  `protobuf:"varint,3,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`         // 机柜ID
	SlotId        int64                  `protobuf:"varint,4,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`                  // 仓位ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCheckBorrowRequest) Reset() {
	*x = PreCheckBorrowRequest{}
	mi := &file_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCheckBorrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCheckBorrowRequest) ProtoMessage() {}

func (x *PreCheckBorrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCheckBorrowRequest.ProtoReflect.Descriptor instead.
func (*PreCheckBorrowRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *PreCheckBorrowRequest) GetPowerBankId() int64 {
	if x != nil {
		return x.PowerBankId
	}
	return 0
}

func (x *PreCheckBorrowRequest) GetStationId() int64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

func (x *PreCheckBorrowRequest) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

func (x *PreCheckBorrowRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

type PreCheckBorrowResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Allowed         bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`                                        // 是否允许租借
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                           // 不允许的原因，allowed=true时为空
	DepositRequired int64                  `protobuf:"varint,3,opt,name=deposit_required,json=depositRequired,proto3" json:"deposit_required,omitempty"` // 所需押金（分），0表示不需要
	StartFee        int64                  `protobuf:"varint,4,opt,name=start_fee,json=startFee,proto3" json:"start_fee,omitempty"`                      // 起步价（分）
	HourlyFee       int64                  `protobuf:"varint,5,opt,name=hourly_fee,json=hourlyFee,proto3" json:"hourly_fee,omitempty"`                   // 每小时费用（分）
	DailyCap        int64                  `protobuf:"varint,6,opt,name=daily_cap,json=dailyCap,proto3" json:"daily_cap,omitempty"`                      // 每日封顶（分）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreCheckBorrowResponse) Reset() {
	*x = PreCheckBorrowResponse{}
	mi := &file_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCheckBorrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCheckBorrowResponse) ProtoMessage() {}

func (x *PreCheckBorrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCheckBorrowResponse.ProtoReflect.Descriptor instead.
func (*PreCheckBorrowResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *PreCheckBorrowResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *PreCheckBorrowResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PreCheckBorrowResponse) GetDepositRequired() int64 {
	if x != nil {
		return x.DepositRequired
	}
	return 0
}

func (x *PreCheckBorrowResponse) GetStartFee() int64 {
	if x != nil {
		return x.StartFee
	}
	return 0
}

func (x *PreCheckBorrowResponse) GetHourlyFee() int64 {
	if x != nil {
		return x.HourlyFee
	}
	return 0
}

func (x *PreCheckBorrowResponse) GetDailyCap() int64 {
	if x != nil {
		return x.DailyCap
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PowerBankId   int64                  `protobuf:"varint,1,opt,name=power_bank_id,json=powerBankId,proto3" json:"power_bank_id,omitempty"` // 充电宝ID
	StationId     int64                  `protobuf:"varint,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`         // 站点ID
	CabinetId     int64                  `protobuf:"varint,3,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`         // 机柜ID
	SlotId        int64                  `protobuf:"varint,4,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`                  // 仓位ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetPowerBankId() int64 {
	if x != nil {
		return x.PowerBankId
	}
	return 0
}

func (x *CreateOrderRequest) GetStationId() int64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

func (x *CreateOrderRequest) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

func (x *CreateOrderRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`                    // 订单号
	StartFee      int64                  `protobuf:"varint,2,opt,name=start_fee,json=startFee,proto3" json:"start_fee,omitempty"`                // 起步价（分）
	HourlyFee     int64                  `protobuf:"varint,3,opt,name=hourly_fee,json=hourlyFee,proto3" json:"hourly_fee,omitempty"`             // 每小时费用（分）
	DailyCap      int64                  `protobuf:"varint,4,opt,name=daily_cap,json=dailyCap,proto3" json:"daily_cap,omitempty"`                // 每日封顶（分）
	DepositFrozen int64                  `protobuf:"varint,5,opt,name=deposit_frozen,json=depositFrozen,proto3" json:"deposit_frozen,omitempty"` // 已冻结押金（分）
	BorrowTime    string                 `protobuf:"bytes,6,opt,name=borrow_time,json=borrowTime,proto3" json:"borrow_time,omitempty"`           // 借出时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateOrderResponse) GetStartFee() int64 {
	if x != nil {
		return x.StartFee
	}
	return 0
}

func (x *CreateOrderResponse) GetHourlyFee() int64 {
	if x != nil {
		return x.HourlyFee
	}
	return 0
}

func (x *CreateOrderResponse) GetDailyCap() int64 {
	if x != nil {
		return x.DailyCap
	}
	return 0
}

func (x *CreateOrderResponse) GetDepositFrozen() int64 {
	if x != nil {
		return x.DepositFrozen
	}
	return 0
}

func (x *CreateOrderResponse) GetBorrowTime() string {
	if x != nil {
		return x.BorrowTime
	}
	return ""
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"` // 订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 操作结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReturnPowerBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`        // 订单号
	StationId     int64                  `protobuf:"varint,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"` // 归还站点ID
	CabinetId     int64                  `protobuf:"varint,3,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"` // 归还机柜ID
	SlotId        int64                  `protobuf:"varint,4,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`          // 归还仓位ID
	CouponId      string                 `protobuf:"bytes,5,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`     // 优惠券ID（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnPowerBankRequest) Reset() {
	*x = ReturnPowerBankRequest{}
	mi := &file_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnPowerBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnPowerBankRequest) ProtoMessage() {}

func (x *ReturnPowerBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnPowerBankRequest.ProtoReflect.Descriptor instead.
func (*ReturnPowerBankRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *ReturnPowerBankRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ReturnPowerBankRequest) GetStationId() int64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

func (x *ReturnPowerBankRequest) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

func (x *ReturnPowerBankRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *ReturnPowerBankRequest) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

type ReturnPowerBankResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderNo         string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`                          // 订单号
	DurationMinutes int64                  `protobuf:"varint,2,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"` // 租借时长（分钟）
	TotalAmount     int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`             // 总费用（分）
	PaidAmount      int64                  `protobuf:"varint,4,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`                // 实付金额（分）
	DiscountAmount  int64                  `protobuf:"varint,5,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`    // 优惠金额（分）
	BalanceDeducted int64                  `protobuf:"varint,6,opt,name=balance_deducted,json=balanceDeducted,proto3" json:"balance_deducted,omitempty"` // 余额扣除（分）
	DepositDeducted int64                  `protobuf:"varint,7,opt,name=deposit_deducted,json=depositDeducted,proto3" json:"deposit_deducted,omitempty"` // 押金扣除（分）
	ReturnTime      string                 `protobuf:"bytes,8,opt,name=return_time,json=returnTime,proto3" json:"return_time,omitempty"`                 // 归还时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReturnPowerBankResponse) Reset() {
	*x = ReturnPowerBankResponse{}
	mi := &file_order_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnPowerBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnPowerBankResponse) ProtoMessage() {}

func (x *ReturnPowerBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnPowerBankResponse.ProtoReflect.Descriptor instead.
func (*ReturnPowerBankResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *ReturnPowerBankResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ReturnPowerBankResponse) GetDurationMinutes() int64 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *ReturnPowerBankResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *ReturnPowerBankResponse) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *ReturnPowerBankResponse) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *ReturnPowerBankResponse) GetBalanceDeducted() int64 {
	if x != nil {
		return x.BalanceDeducted
	}
	return 0
}

func (x *ReturnPowerBankResponse) GetDepositDeducted() int64 {
	if x != nil {
		return x.DepositDeducted
	}
	return 0
}

func (x *ReturnPowerBankResponse) GetReturnTime() string {
	if x != nil {
		return x.ReturnTime
	}
	return ""
}

type ExtendRentalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`                 // 订单号
	ExtraMinutes  int32                  `protobuf:"varint,2,opt,name=extra_minutes,json=extraMinutes,proto3" json:"extra_minutes,omitempty"` // 延长时长（分钟）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendRentalRequest) Reset() {
	*x = ExtendRentalRequest{}
	mi := &file_order_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendRentalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendRentalRequest) ProtoMessage() {}

func (x *ExtendRentalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendRentalRequest.ProtoReflect.Descriptor instead.
func (*ExtendRentalRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *ExtendRentalRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ExtendRentalRequest) GetExtraMinutes() int32 {
	if x != nil {
		return x.ExtraMinutes
	}
	return 0
}

type ExtendRentalResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Message           string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                               // 操作结果
	AdditionalDeposit int64                  `protobuf:"varint,2,opt,name=additional_deposit,json=additionalDeposit,proto3" json:"additional_deposit,omitempty"` // 额外冻结押金（分）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExtendRentalResponse) Reset() {
	*x = ExtendRentalResponse{}
	mi := &file_order_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendRentalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendRentalResponse) ProtoMessage() {}

func (x *ExtendRentalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendRentalResponse.ProtoReflect.Descriptor instead.
func (*ExtendRentalResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *ExtendRentalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExtendRentalResponse) GetAdditionalDeposit() int64 {
	if x != nil {
		return x.AdditionalDeposit
	}
	return 0
}

type GetCurrentOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentOrderRequest) Reset() {
	*x = GetCurrentOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentOrderRequest) ProtoMessage() {}

func (x *GetCurrentOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentOrderRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{10}
}

type GetCurrentOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"` // 当前进行中的订单，无则返回null
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentOrderResponse) Reset() {
	*x = GetCurrentOrderResponse{}
	mi := &file_order_v1_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentOrderResponse) ProtoMessage() {}

func (x *GetCurrentOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentOrderResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{11}
}

func (x *GetCurrentOrderResponse) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetRealTimeFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"` // 订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealTimeFeeRequest) Reset() {
	*x = GetRealTimeFeeRequest{}
	mi := &file_order_v1_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealTimeFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealTimeFeeRequest) ProtoMessage() {}

func (x *GetRealTimeFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealTimeFeeRequest.ProtoReflect.Descriptor instead.
func (*GetRealTimeFeeRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{12}
}

func (x *GetRealTimeFeeRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetRealTimeFeeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderNo        string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`                       // 订单号
	ElapsedSeconds int64                  `protobuf:"varint,2,opt,name=elapsed_seconds,json=elapsedSeconds,proto3" json:"elapsed_seconds,omitempty"` // 已租借秒数
	CurrentFee     int64                  `protobuf:"varint,3,opt,name=current_fee,json=currentFee,proto3" json:"current_fee,omitempty"`             // 当前费用（分）
	DailyCap       int64                  `protobuf:"varint,4,opt,name=daily_cap,json=dailyCap,proto3" json:"daily_cap,omitempty"`                   // 每日封顶（分）
	HourlyFee      int64                  `protobuf:"varint,5,opt,name=hourly_fee,json=hourlyFee,proto3" json:"hourly_fee,omitempty"`                // 每小时费用（分）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRealTimeFeeResponse) Reset() {
	*x = GetRealTimeFeeResponse{}
	mi := &file_order_v1_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealTimeFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealTimeFeeResponse) ProtoMessage() {}

func (x *GetRealTimeFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealTimeFeeResponse.ProtoReflect.Descriptor instead.
func (*GetRealTimeFeeResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{13}
}

func (x *GetRealTimeFeeResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetRealTimeFeeResponse) GetElapsedSeconds() int64 {
	if x != nil {
		return x.ElapsedSeconds
	}
	return 0
}

func (x *GetRealTimeFeeResponse) GetCurrentFee() int64 {
	if x != nil {
		return x.CurrentFee
	}
	return 0
}

func (x *GetRealTimeFeeResponse) GetDailyCap() int64 {
	if x != nil {
		return x.DailyCap
	}
	return 0
}

func (x *GetRealTimeFeeResponse) GetHourlyFee() int64 {
	if x != nil {
		return x.HourlyFee
	}
	return 0
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                      // 筛选状态：borrowed-进行中 completed-已完成 pending_compensation-待赔付
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_order_v1_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{14}
}

func (x *ListOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`                          // 订单列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总记录数
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_order_v1_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{15}
}

func (x *ListOrdersResponse) GetList() []*OrderInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListOrdersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrdersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CreateCompensationPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"` // 订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompensationPaymentRequest) Reset() {
	*x = CreateCompensationPaymentRequest{}
	mi := &file_order_v1_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompensationPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompensationPaymentRequest) ProtoMessage() {}

func (x *CreateCompensationPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompensationPaymentRequest.ProtoReflect.Descriptor instead.
func (*CreateCompensationPaymentRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{16}
}

func (x *CreateCompensationPaymentRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type CreateCompensationPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentUrl    string                 `protobuf:"bytes,1,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"` // 支付链接
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                          // 赔付金额（分）
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`                         // 支付渠道
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompensationPaymentResponse) Reset() {
	*x = CreateCompensationPaymentResponse{}
	mi := &file_order_v1_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompensationPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompensationPaymentResponse) ProtoMessage() {}

func (x *CreateCompensationPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompensationPaymentResponse.ProtoReflect.Descriptor instead.
func (*CreateCompensationPaymentResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCompensationPaymentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *CreateCompensationPaymentResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateCompensationPaymentResponse) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type GetStationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 站点ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStationRequest) Reset() {
	*x = GetStationRequest{}
	mi := &file_order_v1_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationRequest) ProtoMessage() {}

func (x *GetStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationRequest.ProtoReflect.Descriptor instead.
func (*GetStationRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{18}
}

func (x *GetStationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetStationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Station       *StationInfo           `protobuf:"bytes,1,opt,name=station,proto3" json:"station,omitempty"` // 站点信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStationResponse) Reset() {
	*x = GetStationResponse{}
	mi := &file_order_v1_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationResponse) ProtoMessage() {}

func (x *GetStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationResponse.ProtoReflect.Descriptor instead.
func (*GetStationResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{19}
}

func (x *GetStationResponse) GetStation() *StationInfo {
	if x != nil {
		return x.Station
	}
	return nil
}

type ListNearbyStationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`                            // 纬度
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`                          // 经度
	RadiusMeters  int32                  `protobuf:"varint,3,opt,name=radius_meters,json=radiusMeters,proto3" json:"radius_meters,omitempty"` // 搜索半径（米），默认5000，最大50000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNearbyStationsRequest) Reset() {
	*x = ListNearbyStationsRequest{}
	mi := &file_order_v1_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNearbyStationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNearbyStationsRequest) ProtoMessage() {}

func (x *ListNearbyStationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNearbyStationsRequest.ProtoReflect.Descriptor instead.
func (*ListNearbyStationsRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{20}
}

func (x *ListNearbyStationsRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ListNearbyStationsRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *ListNearbyStationsRequest) GetRadiusMeters() int32 {
	if x != nil {
		return x.RadiusMeters
	}
	return 0
}

type ListNearbyStationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*StationInfo         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"` // 站点列表（按距离由近到远排序）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNearbyStationsResponse) Reset() {
	*x = ListNearbyStationsResponse{}
	mi := &file_order_v1_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNearbyStationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNearbyStationsResponse) ProtoMessage() {}

func (x *ListNearbyStationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNearbyStationsResponse.ProtoReflect.Descriptor instead.
func (*ListNearbyStationsResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{21}
}

func (x *ListNearbyStationsResponse) GetList() []*StationInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type StationInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                               // 站点ID
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                            // 站点名称
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                                      // 详细地址
	Latitude       float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`                                  // 纬度
	Longitude      float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`                                // 经度
	Distance       float64                `protobuf:"fixed64,6,opt,name=distance,proto3" json:"distance,omitempty"`                                  // 距离（米），ListNearbyStations时返回
	AvailableBanks int32                  `protobuf:"varint,7,opt,name=available_banks,json=availableBanks,proto3" json:"available_banks,omitempty"` // 空闲充电宝数量
	OpenTime       string                 `protobuf:"bytes,8,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`                   // 营业时间
	Description    string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`                              // 站点介绍
	Images         string                 `protobuf:"bytes,10,opt,name=images,proto3" json:"images,omitempty"`                                       // 图片JSON数组
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StationInfo) Reset() {
	*x = StationInfo{}
	mi := &file_order_v1_order_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationInfo) ProtoMessage() {}

func (x *StationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationInfo.ProtoReflect.Descriptor instead.
func (*StationInfo) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{22}
}

func (x *StationInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StationInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *StationInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *StationInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *StationInfo) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *StationInfo) GetAvailableBanks() int32 {
	if x != nil {
		return x.AvailableBanks
	}
	return 0
}

func (x *StationInfo) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *StationInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StationInfo) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

type ScanCabinetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CabinetId     int64                  `protobuf:"varint,1,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"` // 二维码中解析出的机柜ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanCabinetRequest) Reset() {
	*x = ScanCabinetRequest{}
	mi := &file_order_v1_order_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanCabinetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanCabinetRequest) ProtoMessage() {}

func (x *ScanCabinetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanCabinetRequest.ProtoReflect.Descriptor instead.
func (*ScanCabinetRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{23}
}

func (x *ScanCabinetRequest) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

type ScanCabinetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 站点信息
	StationId      int64  `protobuf:"varint,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	StationName    string `protobuf:"bytes,2,opt,name=station_name,json=stationName,proto3" json:"station_name,omitempty"`
	StationAddress string `protobuf:"bytes,3,opt,name=station_address,json=stationAddress,proto3" json:"station_address,omitempty"`
	// 机柜信息
	CabinetId      int64  `protobuf:"varint,4,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`
	CabinetNo      string `protobuf:"bytes,5,opt,name=cabinet_no,json=cabinetNo,proto3" json:"cabinet_no,omitempty"`
	AvailableSlots int32  `protobuf:"varint,6,opt,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"`
	TotalSlots     int32  `protobuf:"varint,7,opt,name=total_slots,json=totalSlots,proto3" json:"total_slots,omitempty"`
	// 计价规则
	StartFee      int64 `protobuf:"varint,8,opt,name=start_fee,json=startFee,proto3" json:"start_fee,omitempty"`     // 起步价（分）
	StartMins     int32 `protobuf:"varint,9,opt,name=start_mins,json=startMins,proto3" json:"start_mins,omitempty"`  // 起步时长（分钟）
	HourlyFee     int64 `protobuf:"varint,10,opt,name=hourly_fee,json=hourlyFee,proto3" json:"hourly_fee,omitempty"` // 每小时费用（分）
	DailyCap      int64 `protobuf:"varint,11,opt,name=daily_cap,json=dailyCap,proto3" json:"daily_cap,omitempty"`    // 每日封顶（分）
	Deposit       int64 `protobuf:"varint,12,opt,name=deposit,proto3" json:"deposit,omitempty"`                      // 押金（分）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanCabinetResponse) Reset() {
	*x = ScanCabinetResponse{}
	mi := &file_order_v1_order_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanCabinetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanCabinetResponse) ProtoMessage() {}

func (x *ScanCabinetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanCabinetResponse.ProtoReflect.Descriptor instead.
func (*ScanCabinetResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{24}
}

func (x *ScanCabinetResponse) GetStationId() int64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

func (x *ScanCabinetResponse) GetStationName() string {
	if x != nil {
		return x.StationName
	}
	return ""
}

func (x *ScanCabinetResponse) GetStationAddress() string {
	if x != nil {
		return x.StationAddress
	}
	return ""
}

func (x *ScanCabinetResponse) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

func (x *ScanCabinetResponse) GetCabinetNo() string {
	if x != nil {
		return x.CabinetNo
	}
	return ""
}

func (x *ScanCabinetResponse) GetAvailableSlots() int32 {
	if x != nil {
		return x.AvailableSlots
	}
	return 0
}

func (x *ScanCabinetResponse) GetTotalSlots() int32 {
	if x != nil {
		return x.TotalSlots
	}
	return 0
}

func (x *ScanCabinetResponse) GetStartFee() int64 {
	if x != nil {
		return x.StartFee
	}
	return 0
}

func (x *ScanCabinetResponse) GetStartMins() int32 {
	if x != nil {
		return x.StartMins
	}
	return 0
}

func (x *ScanCabinetResponse) GetHourlyFee() int64 {
	if x != nil {
		return x.HourlyFee
	}
	return 0
}

func (x *ScanCabinetResponse) GetDailyCap() int64 {
	if x != nil {
		return x.DailyCap
	}
	return 0
}

func (x *ScanCabinetResponse) GetDeposit() int64 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

type OrderInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                         // ID
	OrderNo           string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`                                 // 订单号
	UserId            int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                   // 用户ID
	PowerBankId       int64                  `protobuf:"varint,4,opt,name=power_bank_id,json=powerBankId,proto3" json:"power_bank_id,omitempty"`                  // 充电宝ID
	PowerBankNo       string                 `protobuf:"bytes,5,opt,name=power_bank_no,json=powerBankNo,proto3" json:"power_bank_no,omitempty"`                   // 充电宝编号
	BorrowStationId   int64                  `protobuf:"varint,6,opt,name=borrow_station_id,json=borrowStationId,proto3" json:"borrow_station_id,omitempty"`      // 借出站点ID
	BorrowStationName string                 `protobuf:"bytes,7,opt,name=borrow_station_name,json=borrowStationName,proto3" json:"borrow_station_name,omitempty"` // 借出站点名称
	ReturnStationId   int64                  `protobuf:"varint,8,opt,name=return_station_id,json=returnStationId,proto3" json:"return_station_id,omitempty"`      // 归还站点ID
	ReturnStationName string                 `protobuf:"bytes,9,opt,name=return_station_name,json=returnStationName,proto3" json:"return_station_name,omitempty"` // 归还站点名称
	BorrowTime        string                 `protobuf:"bytes,10,opt,name=borrow_time,json=borrowTime,proto3" json:"borrow_time,omitempty"`                       // 借出时间
	ReturnTime        string                 `protobuf:"bytes,11,opt,name=return_time,json=returnTime,proto3" json:"return_time,omitempty"`                       // 归还时间
	DurationMinutes   int32                  `protobuf:"varint,12,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`       // 租借时长（分钟）
	StartFee          int64                  `protobuf:"varint,13,opt,name=start_fee,json=startFee,proto3" json:"start_fee,omitempty"`                            // 起步价（分）
	HourlyFee         int64                  `protobuf:"varint,14,opt,name=hourly_fee,json=hourlyFee,proto3" json:"hourly_fee,omitempty"`                         // 每小时费用（分）
	TotalAmount       int64                  `protobuf:"varint,15,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`                   // 总费用（分）
	PaidAmount        int64                  `protobuf:"varint,16,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`                      // 实付金额（分）
	Status            string                 `protobuf:"bytes,17,opt,name=status,proto3" json:"status,omitempty"`                                                 // 状态
	Remark            string                 `protobuf:"bytes,18,opt,name=remark,proto3" json:"remark,omitempty"`                                                 // 备注
	DiscountAmount    int64                  `protobuf:"varint,19,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`          // 优惠金额（分）
	DailyCap          int64                  `protobuf:"varint,20,opt,name=daily_cap,json=dailyCap,proto3" json:"daily_cap,omitempty"`                            // 每日封顶（分）
	CreatedAt         string                 `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                          // 创建时间
	UpdatedAt         string                 `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                          // 更新时间
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_order_v1_order_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{25}
}

func (x *OrderInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfo) GetPowerBankId() int64 {
	if x != nil {
		return x.PowerBankId
	}
	return 0
}

func (x *OrderInfo) GetPowerBankNo() string {
	if x != nil {
		return x.PowerBankNo
	}
	return ""
}

func (x *OrderInfo) GetBorrowStationId() int64 {
	if x != nil {
		return x.BorrowStationId
	}
	return 0
}

func (x *OrderInfo) GetBorrowStationName() string {
	if x != nil {
		return x.BorrowStationName
	}
	return ""
}

func (x *OrderInfo) GetReturnStationId() int64 {
	if x != nil {
		return x.ReturnStationId
	}
	return 0
}

func (x *OrderInfo) GetReturnStationName() string {
	if x != nil {
		return x.ReturnStationName
	}
	return ""
}

func (x *OrderInfo) GetBorrowTime() string {
	if x != nil {
		return x.BorrowTime
	}
	return ""
}

func (x *OrderInfo) GetReturnTime() string {
	if x != nil {
		return x.ReturnTime
	}
	return ""
}

func (x *OrderInfo) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *OrderInfo) GetStartFee() int64 {
	if x != nil {
		return x.StartFee
	}
	return 0
}

func (x *OrderInfo) GetHourlyFee() int64 {
	if x != nil {
		return x.HourlyFee
	}
	return 0
}

func (x *OrderInfo) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderInfo) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *OrderInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderInfo) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *OrderInfo) GetDailyCap() int64 {
	if x != nil {
		return x.DailyCap
	}
	return 0
}

func (x *OrderInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetOrderDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"` // 订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailRequest) Reset() {
	*x = GetOrderDetailRequest{}
	mi := &file_order_v1_order_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailRequest) ProtoMessage() {}

func (x *GetOrderDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailRequest.ProtoReflect.Descriptor instead.
func (*GetOrderDetailRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{26}
}

func (x *GetOrderDetailRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type OrderDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo           string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId            int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PowerBankId       int64                  `protobuf:"varint,4,opt,name=power_bank_id,json=powerBankId,proto3" json:"power_bank_id,omitempty"`
	PowerBankNo       string                 `protobuf:"bytes,5,opt,name=power_bank_no,json=powerBankNo,proto3" json:"power_bank_no,omitempty"`
	BorrowStationId   int64                  `protobuf:"varint,6,opt,name=borrow_station_id,json=borrowStationId,proto3" json:"borrow_station_id,omitempty"`
	BorrowStationName string                 `protobuf:"bytes,7,opt,name=borrow_station_name,json=borrowStationName,proto3" json:"borrow_station_name,omitempty"`
	BorrowCabinetId   int64                  `protobuf:"varint,8,opt,name=borrow_cabinet_id,json=borrowCabinetId,proto3" json:"borrow_cabinet_id,omitempty"`
	BorrowCabinetNo   string                 `protobuf:"bytes,9,opt,name=borrow_cabinet_no,json=borrowCabinetNo,proto3" json:"borrow_cabinet_no,omitempty"`
	BorrowSlotId      int64                  `protobuf:"varint,10,opt,name=borrow_slot_id,json=borrowSlotId,proto3" json:"borrow_slot_id,omitempty"`
	BorrowSlotNo      string                 `protobuf:"bytes,11,opt,name=borrow_slot_no,json=borrowSlotNo,proto3" json:"borrow_slot_no,omitempty"`
	ReturnStationId   int64                  `protobuf:"varint,12,opt,name=return_station_id,json=returnStationId,proto3" json:"return_station_id,omitempty"`
	ReturnStationName string                 `protobuf:"bytes,13,opt,name=return_station_name,json=returnStationName,proto3" json:"return_station_name,omitempty"`
	ReturnCabinetId   int64                  `protobuf:"varint,14,opt,name=return_cabinet_id,json=returnCabinetId,proto3" json:"return_cabinet_id,omitempty"`
	ReturnCabinetNo   string                 `protobuf:"bytes,15,opt,name=return_cabinet_no,json=returnCabinetNo,proto3" json:"return_cabinet_no,omitempty"`
	ReturnSlotId      int64                  `protobuf:"varint,16,opt,name=return_slot_id,json=returnSlotId,proto3" json:"return_slot_id,omitempty"`
	ReturnSlotNo      string                 `protobuf:"bytes,17,opt,name=return_slot_no,json=returnSlotNo,proto3" json:"return_slot_no,omitempty"`
	BorrowTime        string                 `protobuf:"bytes,18,opt,name=borrow_time,json=borrowTime,proto3" json:"borrow_time,omitempty"`
	ReturnTime        string                 `protobuf:"bytes,19,opt,name=return_time,json=returnTime,proto3" json:"return_time,omitempty"`
	DurationMinutes   int32                  `protobuf:"varint,20,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	StartFee          int64                  `protobuf:"varint,21,opt,name=start_fee,json=startFee,proto3" json:"start_fee,omitempty"`
	HourlyFee         int64                  `protobuf:"varint,22,opt,name=hourly_fee,json=hourlyFee,proto3" json:"hourly_fee,omitempty"`
	DailyCap          int64                  `protobuf:"varint,23,opt,name=daily_cap,json=dailyCap,proto3" json:"daily_cap,omitempty"`
	TotalAmount       int64                  `protobuf:"varint,24,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PaidAmount        int64                  `protobuf:"varint,25,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	DiscountAmount    int64                  `protobuf:"varint,26,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	Deposit           int64                  `protobuf:"varint,27,opt,name=deposit,proto3" json:"deposit,omitempty"`
	Status            string                 `protobuf:"bytes,28,opt,name=status,proto3" json:"status,omitempty"`
	Remark            string                 `protobuf:"bytes,29,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,30,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,31,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrderDetail) Reset() {
	*x = OrderDetail{}
	mi := &file_order_v1_order_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetail) ProtoMessage() {}

func (x *OrderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetail.ProtoReflect.Descriptor instead.
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{27}
}

func (x *OrderDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderDetail) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderDetail) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderDetail) GetPowerBankId() int64 {
	if x != nil {
		return x.PowerBankId
	}
	return 0
}

func (x *OrderDetail) GetPowerBankNo() string {
	if x != nil {
		return x.PowerBankNo
	}
	return ""
}

func (x *OrderDetail) GetBorrowStationId() int64 {
	if x != nil {
		return x.BorrowStationId
	}
	return 0
}

func (x *OrderDetail) GetBorrowStationName() string {
	if x != nil {
		return x.BorrowStationName
	}
	return ""
}

func (x *OrderDetail) GetBorrowCabinetId() int64 {
	if x != nil {
		return x.BorrowCabinetId
	}
	return 0
}

func (x *OrderDetail) GetBorrowCabinetNo() string {
	if x != nil {
		return x.BorrowCabinetNo
	}
	return ""
}

func (x *OrderDetail) GetBorrowSlotId() int64 {
	if x != nil {
		return x.BorrowSlotId
	}
	return 0
}

func (x *OrderDetail) GetBorrowSlotNo() string {
	if x != nil {
		return x.BorrowSlotNo
	}
	return ""
}

func (x *OrderDetail) GetReturnStationId() int64 {
	if x != nil {
		return x.ReturnStationId
	}
	return 0
}

func (x *OrderDetail) GetReturnStationName() string {
	if x != nil {
		return x.ReturnStationName
	}
	return ""
}

func (x *OrderDetail) GetReturnCabinetId() int64 {
	if x != nil {
		return x.ReturnCabinetId
	}
	return 0
}

func (x *OrderDetail) GetReturnCabinetNo() string {
	if x != nil {
		return x.ReturnCabinetNo
	}
	return ""
}

func (x *OrderDetail) GetReturnSlotId() int64 {
	if x != nil {
		return x.ReturnSlotId
	}
	return 0
}

func (x *OrderDetail) GetReturnSlotNo() string {
	if x != nil {
		return x.ReturnSlotNo
	}
	return ""
}

func (x *OrderDetail) GetBorrowTime() string {
	if x != nil {
		return x.BorrowTime
	}
	return ""
}

func (x *OrderDetail) GetReturnTime() string {
	if x != nil {
		return x.ReturnTime
	}
	return ""
}

func (x *OrderDetail) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *OrderDetail) GetStartFee() int64 {
	if x != nil {
		return x.StartFee
	}
	return 0
}

func (x *OrderDetail) GetHourlyFee() int64 {
	if x != nil {
		return x.HourlyFee
	}
	return 0
}

func (x *OrderDetail) GetDailyCap() int64 {
	if x != nil {
		return x.DailyCap
	}
	return 0
}

func (x *OrderDetail) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderDetail) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *OrderDetail) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *OrderDetail) GetDeposit() int64 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

func (x *OrderDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderDetail) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetOrderDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderDetail           `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailResponse) Reset() {
	*x = GetOrderDetailResponse{}
	mi := &file_order_v1_order_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailResponse) ProtoMessage() {}

func (x *GetOrderDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailResponse.ProtoReflect.Descriptor instead.
func (*GetOrderDetailResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{28}
}

func (x *GetOrderDetailResponse) GetOrder() *OrderDetail {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetCabinetListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     int64                  `protobuf:"varint,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"` // 站点ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCabinetListRequest) Reset() {
	*x = GetCabinetListRequest{}
	mi := &file_order_v1_order_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCabinetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCabinetListRequest) ProtoMessage() {}

func (x *GetCabinetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCabinetListRequest.ProtoReflect.Descriptor instead.
func (*GetCabinetListRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{29}
}

func (x *GetCabinetListRequest) GetStationId() int64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

type CabinetInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                               // 机柜ID
	CabinetNo      string                 `protobuf:"bytes,2,opt,name=cabinet_no,json=cabinetNo,proto3" json:"cabinet_no,omitempty"`                 // 机柜编号
	Status         int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                                       // 状态：1-正常 2-离线
	TotalSlots     int32                  `protobuf:"varint,4,opt,name=total_slots,json=totalSlots,proto3" json:"total_slots,omitempty"`             // 总仓位数
	AvailableSlots int32                  `protobuf:"varint,5,opt,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"` // 空闲仓位数
	OccupiedSlots  int32                  `protobuf:"varint,6,opt,name=occupied_slots,json=occupiedSlots,proto3" json:"occupied_slots,omitempty"`    // 已占用仓位数
	Slots          []*SlotInfo            `protobuf:"bytes,7,rep,name=slots,proto3" json:"slots,omitempty"`                                          // 仓位列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CabinetInfo) Reset() {
	*x = CabinetInfo{}
	mi := &file_order_v1_order_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CabinetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CabinetInfo) ProtoMessage() {}

func (x *CabinetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CabinetInfo.ProtoReflect.Descriptor instead.
func (*CabinetInfo) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{30}
}

func (x *CabinetInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CabinetInfo) GetCabinetNo() string {
	if x != nil {
		return x.CabinetNo
	}
	return ""
}

func (x *CabinetInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CabinetInfo) GetTotalSlots() int32 {
	if x != nil {
		return x.TotalSlots
	}
	return 0
}

func (x *CabinetInfo) GetAvailableSlots() int32 {
	if x != nil {
		return x.AvailableSlots
	}
	return 0
}

func (x *CabinetInfo) GetOccupiedSlots() int32 {
	if x != nil {
		return x.OccupiedSlots
	}
	return 0
}

func (x *CabinetInfo) GetSlots() []*SlotInfo {
	if x != nil {
		return x.Slots
	}
	return nil
}

type SlotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                         // 仓位ID
	SlotNo        string                 `protobuf:"bytes,2,opt,name=slot_no,json=slotNo,proto3" json:"slot_no,omitempty"`                    // 仓位编号
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                  // 状态：empty/occupied/disabled
	PowerBankId   int64                  `protobuf:"varint,4,opt,name=power_bank_id,json=powerBankId,proto3" json:"power_bank_id,omitempty"`  // 充电宝ID（空仓位为0）
	PowerBankNo   string                 `protobuf:"bytes,5,opt,name=power_bank_no,json=powerBankNo,proto3" json:"power_bank_no,omitempty"`   // 充电宝编号
	BatteryLevel  int32                  `protobuf:"varint,6,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"` // 电量百分比
	Power         string                 `protobuf:"bytes,7,opt,name=power,proto3" json:"power,omitempty"`                                    // 充电功率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotInfo) Reset() {
	*x = SlotInfo{}
	mi := &file_order_v1_order_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotInfo) ProtoMessage() {}

func (x *SlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotInfo.ProtoReflect.Descriptor instead.
func (*SlotInfo) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{31}
}

func (x *SlotInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SlotInfo) GetSlotNo() string {
	if x != nil {
		return x.SlotNo
	}
	return ""
}

func (x *SlotInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SlotInfo) GetPowerBankId() int64 {
	if x != nil {
		return x.PowerBankId
	}
	return 0
}

func (x *SlotInfo) GetPowerBankNo() string {
	if x != nil {
		return x.PowerBankNo
	}
	return ""
}

func (x *SlotInfo) GetBatteryLevel() int32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *SlotInfo) GetPower() string {
	if x != nil {
		return x.Power
	}
	return ""
}

type GetCabinetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cabinets      []*CabinetInfo         `protobuf:"bytes,1,rep,name=cabinets,proto3" json:"cabinets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCabinetListResponse) Reset() {
	*x = GetCabinetListResponse{}
	mi := &file_order_v1_order_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCabinetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCabinetListResponse) ProtoMessage() {}

func (x *GetCabinetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCabinetListResponse.ProtoReflect.Descriptor instead.
func (*GetCabinetListResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{32}
}

func (x *GetCabinetListResponse) GetCabinets() []*CabinetInfo {
	if x != nil {
		return x.Cabinets
	}
	return nil
}

type GetDelayFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`                 // 订单号
	ExtraMinutes  int32                  `protobuf:"varint,2,opt,name=extra_minutes,json=extraMinutes,proto3" json:"extra_minutes,omitempty"` // 延长时长（分钟）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelayFeeRequest) Reset() {
	*x = GetDelayFeeRequest{}
	mi := &file_order_v1_order_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelayFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelayFeeRequest) ProtoMessage() {}

func (x *GetDelayFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelayFeeRequest.ProtoReflect.Descriptor instead.
func (*GetDelayFeeRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{33}
}

func (x *GetDelayFeeRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetDelayFeeRequest) GetExtraMinutes() int32 {
	if x != nil {
		return x.ExtraMinutes
	}
	return 0
}

type GetDelayFeeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderNo           string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`                                // 订单号
	ExtraMinutes      int32                  `protobuf:"varint,2,opt,name=extra_minutes,json=extraMinutes,proto3" json:"extra_minutes,omitempty"`                // 延长时长（分钟）
	AdditionalFee     int64                  `protobuf:"varint,3,opt,name=additional_fee,json=additionalFee,proto3" json:"additional_fee,omitempty"`             // 额外费用（分）
	EstimatedTotal    int64                  `protobuf:"varint,4,opt,name=estimated_total,json=estimatedTotal,proto3" json:"estimated_total,omitempty"`          // 预估总费用（分）
	AdditionalDeposit int64                  `protobuf:"varint,5,opt,name=additional_deposit,json=additionalDeposit,proto3" json:"additional_deposit,omitempty"` // 额外需冻结押金（分）
	HourlyFee         int64                  `protobuf:"varint,6,opt,name=hourly_fee,json=hourlyFee,proto3" json:"hourly_fee,omitempty"`                         // 每小时费用（分）
	DailyCap          int64                  `protobuf:"varint,7,opt,name=daily_cap,json=dailyCap,proto3" json:"daily_cap,omitempty"`                            // 每日封顶（分）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetDelayFeeResponse) Reset() {
	*x = GetDelayFeeResponse{}
	mi := &file_order_v1_order_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelayFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelayFeeResponse) ProtoMessage() {}

func (x *GetDelayFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelayFeeResponse.ProtoReflect.Descriptor instead.
func (*GetDelayFeeResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{34}
}

func (x *GetDelayFeeResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetDelayFeeResponse) GetExtraMinutes() int32 {
	if x != nil {
		return x.ExtraMinutes
	}
	return 0
}

func (x *GetDelayFeeResponse) GetAdditionalFee() int64 {
	if x != nil {
		return x.AdditionalFee
	}
	return 0
}

func (x *GetDelayFeeResponse) GetEstimatedTotal() int64 {
	if x != nil {
		return x.EstimatedTotal
	}
	return 0
}

func (x *GetDelayFeeResponse) GetAdditionalDeposit() int64 {
	if x != nil {
		return x.AdditionalDeposit
	}
	return 0
}

func (x *GetDelayFeeResponse) GetHourlyFee() int64 {
	if x != nil {
		return x.HourlyFee
	}
	return 0
}

func (x *GetDelayFeeResponse) GetDailyCap() int64 {
	if x != nil {
		return x.DailyCap
	}
	return 0
}

var File_order_v1_order_proto protoreflect.FileDescriptor

const file_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x14order/v1/order.proto\x12\border.v1\x1a\x1cgoogle/api/annotations.proto\"\x92\x01\n" +
	"\x15PreCheckBorrowRequest\x12\"\n" +
	"\rpower_bank_id\x18\x01 \x01(\x03R\vpowerBankId\x12\x1d\n" +
	"\n" +
	"station_id\x18\x02 \x01(\x03R\tstationId\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x03 \x01(\x03R\tcabinetId\x12\x17\n" +
	"\aslot_id\x18\x04 \x01(\x03R\x06slotId\"\xce\x01\n" +
	"\x16PreCheckBorrowResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12)\n" +
	"\x10deposit_required\x18\x03 \x01(\x03R\x0fdepositRequired\x12\x1b\n" +
	"\tstart_fee\x18\x04 \x01(\x03R\bstartFee\x12\x1d\n" +
	"\n" +
	"hourly_fee\x18\x05 \x01(\x03R\thourlyFee\x12\x1b\n" +
	"\tdaily_cap\x18\x06 \x01(\x03R\bdailyCap\"\x8f\x01\n" +
	"\x12CreateOrderRequest\x12\"\n" +
	"\rpower_bank_id\x18\x01 \x01(\x03R\vpowerBankId\x12\x1d\n" +
	"\n" +
	"station_id\x18\x02 \x01(\x03R\tstationId\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x03 \x01(\x03R\tcabinetId\x12\x17\n" +
	"\aslot_id\x18\x04 \x01(\x03R\x06slotId\"\xd1\x01\n" +
	"\x13CreateOrderResponse\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1b\n" +
	"\tstart_fee\x18\x02 \x01(\x03R\bstartFee\x12\x1d\n" +
	"\n" +
	"hourly_fee\x18\x03 \x01(\x03R\thourlyFee\x12\x1b\n" +
	"\tdaily_cap\x18\x04 \x01(\x03R\bdailyCap\x12%\n" +
	"\x0edeposit_frozen\x18\x05 \x01(\x03R\rdepositFrozen\x12\x1f\n" +
	"\vborrow_time\x18\x06 \x01(\tR\n" +
	"borrowTime\"/\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"/\n" +
	"\x13CancelOrderResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa7\x01\n" +
	"\x16ReturnPowerBankRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"station_id\x18\x02 \x01(\x03R\tstationId\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x03 \x01(\x03R\tcabinetId\x12\x17\n" +
	"\aslot_id\x18\x04 \x01(\x03R\x06slotId\x12\x1b\n" +
	"\tcoupon_id\x18\x05 \x01(\tR\bcouponId\"\xc3\x02\n" +
	"\x17ReturnPowerBankResponse\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12)\n" +
	"\x10duration_minutes\x18\x02 \x01(\x03R\x0fdurationMinutes\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\x12\x1f\n" +
	"\vpaid_amount\x18\x04 \x01(\x03R\n" +
	"paidAmount\x12'\n" +
	"\x0fdiscount_amount\x18\x05 \x01(\x03R\x0ediscountAmount\x12)\n" +
	"\x10balance_deducted\x18\x06 \x01(\x03R\x0fbalanceDeducted\x12)\n" +
	"\x10deposit_deducted\x18\a \x01(\x03R\x0fdepositDeducted\x12\x1f\n" +
	"\vreturn_time\x18\b \x01(\tR\n" +
	"returnTime\"U\n" +
	"\x13ExtendRentalRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12#\n" +
	"\rextra_minutes\x18\x02 \x01(\x05R\fextraMinutes\"_\n" +
	"\x14ExtendRentalResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12-\n" +
	"\x12additional_deposit\x18\x02 \x01(\x03R\x11additionalDeposit\"\x18\n" +
	"\x16GetCurrentOrderRequest\"D\n" +
	"\x17GetCurrentOrderResponse\x12)\n" +
	"\x05order\x18\x01 \x01(\v2\x13.order.v1.OrderInfoR\x05order\"2\n" +
	"\x15GetRealTimeFeeRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"\xb9\x01\n" +
	"\x16GetRealTimeFeeResponse\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12'\n" +
	"\x0felapsed_seconds\x18\x02 \x01(\x03R\x0eelapsedSeconds\x12\x1f\n" +
	"\vcurrent_fee\x18\x03 \x01(\x03R\n" +
	"currentFee\x12\x1b\n" +
	"\tdaily_cap\x18\x04 \x01(\x03R\bdailyCap\x12\x1d\n" +
	"\n" +
	"hourly_fee\x18\x05 \x01(\x03R\thourlyFee\"\\\n" +
	"\x11ListOrdersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x84\x01\n" +
	"\x12ListOrdersResponse\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.order.v1.OrderInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"=\n" +
	" CreateCompensationPaymentRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"v\n" +
	"!CreateCompensationPaymentResponse\x12\x1f\n" +
	"\vpayment_url\x18\x01 \x01(\tR\n" +
	"paymentUrl\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\"#\n" +
	"\x11GetStationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"E\n" +
	"\x12GetStationResponse\x12/\n" +
	"\astation\x18\x01 \x01(\v2\x15.order.v1.StationInfoR\astation\"z\n" +
	"\x19ListNearbyStationsRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12#\n" +
	"\rradius_meters\x18\x03 \x01(\x05R\fradiusMeters\"G\n" +
	"\x1aListNearbyStationsResponse\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.order.v1.StationInfoR\x04list\"\xca\x01\n" +
	"\vStationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bdistance\x18\x06 \x01(\x01R\bdistance\x12'\n" +
	"\x0favailable_banks\x18\a \x01(\x05R\x0eavailableBanks\"3\n" +
	"\x12ScanCabinetRequest\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x01 \x01(\x03R\tcabinetId\"\x9a\x03\n" +
	"\x13ScanCabinetResponse\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\x03R\tstationId\x12!\n" +
	"\fstation_name\x18\x02 \x01(\tR\vstationName\x12'\n" +
	"\x0fstation_address\x18\x03 \x01(\tR\x0estationAddress\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x04 \x01(\x03R\tcabinetId\x12\x1d\n" +
	"\n" +
	"cabinet_no\x18\x05 \x01(\tR\tcabinetNo\x12'\n" +
	"\x0favailable_slots\x18\x06 \x01(\x05R\x0eavailableSlots\x12\x1f\n" +
	"\vtotal_slots\x18\a \x01(\x05R\n" +
	"totalSlots\x12\x1b\n" +
	"\tstart_fee\x18\b \x01(\x03R\bstartFee\x12\x1d\n" +
	"\n" +
	"start_mins\x18\t \x01(\x05R\tstartMins\x12\x1d\n" +
	"\n" +
	"hourly_fee\x18\n" +
	" \x01(\x03R\thourlyFee\x12\x1b\n" +
	"\tdaily_cap\x18\v \x01(\x03R\bdailyCap\x12\x18\n" +
	"\adeposit\x18\f \x01(\x03R\adeposit\"\xf0\x05\n" +
	"\tOrderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\"\n" +
	"\rpower_bank_id\x18\x04 \x01(\x03R\vpowerBankId\x12\"\n" +
	"\rpower_bank_no\x18\x05 \x01(\tR\vpowerBankNo\x12*\n" +
	"\x11borrow_station_id\x18\x06 \x01(\x03R\x0fborrowStationId\x12.\n" +
	"\x13borrow_station_name\x18\a \x01(\tR\x11borrowStationName\x12*\n" +
	"\x11return_station_id\x18\b \x01(\x03R\x0freturnStationId\x12.\n" +
	"\x13return_station_name\x18\t \x01(\tR\x11returnStationName\x12\x1f\n" +
	"\vborrow_time\x18\n" +
	" \x01(\tR\n" +
	"borrowTime\x12\x1f\n" +
	"\vreturn_time\x18\v \x01(\tR\n" +
	"returnTime\x12)\n" +
	"\x10duration_minutes\x18\f \x01(\x05R\x0fdurationMinutes\x12\x1b\n" +
	"\tstart_fee\x18\r \x01(\x03R\bstartFee\x12\x1d\n" +
	"\n" +
	"hourly_fee\x18\x0e \x01(\x03R\thourlyFee\x12!\n" +
	"\ftotal_amount\x18\x0f \x01(\x03R\vtotalAmount\x12\x1f\n" +
	"\vpaid_amount\x18\x10 \x01(\x03R\n" +
	"paidAmount\x12\x16\n" +
	"\x06status\x18\x11 \x01(\tR\x06status\x12\x16\n" +
	"\x06remark\x18\x12 \x01(\tR\x06remark\x12'\n" +
	"\x0fdiscount_amount\x18\x13 \x01(\x03R\x0ediscountAmount\x12\x1b\n" +
	"\tdaily_cap\x18\x14 \x01(\x03R\bdailyCap\x12\x1d\n" +
	"\n" +
	"created_at\x18\x15 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\tR\tupdatedAt\"2\n" +
	"\x15GetOrderDetailRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"\xd4\b\n" +
	"\vOrderDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\"\n" +
	"\rpower_bank_id\x18\x04 \x01(\x03R\vpowerBankId\x12\"\n" +
	"\rpower_bank_no\x18\x05 \x01(\tR\vpowerBankNo\x12*\n" +
	"\x11borrow_station_id\x18\x06 \x01(\x03R\x0fborrowStationId\x12.\n" +
	"\x13borrow_station_name\x18\a \x01(\tR\x11borrowStationName\x12*\n" +
	"\x11borrow_cabinet_id\x18\b \x01(\x03R\x0fborrowCabinetId\x12*\n" +
	"\x11borrow_cabinet_no\x18\t \x01(\tR\x0fborrowCabinetNo\x12$\n" +
	"\x0eborrow_slot_id\x18\n" +
	" \x01(\x03R\fborrowSlotId\x12$\n" +
	"\x0eborrow_slot_no\x18\v \x01(\tR\fborrowSlotNo\x12*\n" +
	"\x11return_station_id\x18\f \x01(\x03R\x0freturnStationId\x12.\n" +
	"\x13return_station_name\x18\r \x01(\tR\x11returnStationName\x12*\n" +
	"\x11return_cabinet_id\x18\x0e \x01(\x03R\x0freturnCabinetId\x12*\n" +
	"\x11return_cabinet_no\x18\x0f \x01(\tR\x0freturnCabinetNo\x12$\n" +
	"\x0ereturn_slot_id\x18\x10 \x01(\x03R\freturnSlotId\x12$\n" +
	"\x0ereturn_slot_no\x18\x11 \x01(\tR\freturnSlotNo\x12\x1f\n" +
	"\vborrow_time\x18\x12 \x01(\tR\n" +
	"borrowTime\x12\x1f\n" +
	"\vreturn_time\x18\x13 \x01(\tR\n" +
	"returnTime\x12)\n" +
	"\x10duration_minutes\x18\x14 \x01(\x05R\x0fdurationMinutes\x12\x1b\n" +
	"\tstart_fee\x18\x15 \x01(\x03R\bstartFee\x12\x1d\n" +
	"\n" +
	"hourly_fee\x18\x16 \x01(\x03R\thourlyFee\x12\x1b\n" +
	"\tdaily_cap\x18\x17 \x01(\x03R\bdailyCap\x12!\n" +
	"\ftotal_amount\x18\x18 \x01(\x03R\vtotalAmount\x12\x1f\n" +
	"\vpaid_amount\x18\x19 \x01(\x03R\n" +
	"paidAmount\x12'\n" +
	"\x0fdiscount_amount\x18\x1a \x01(\x03R\x0ediscountAmount\x12\x18\n" +
	"\adeposit\x18\x1b \x01(\x03R\adeposit\x12\x16\n" +
	"\x06status\x18\x1c \x01(\tR\x06status\x12\x16\n" +
	"\x06remark\x18\x1d \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\x1e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x1f \x01(\tR\tupdatedAt\"E\n" +
	"\x16GetOrderDetailResponse\x12+\n" +
	"\x05order\x18\x01 \x01(\v2\x15.order.v1.OrderDetailR\x05order\"6\n" +
	"\x15GetCabinetListRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\x03R\tstationId\"\xef\x01\n" +
	"\vCabinetInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"cabinet_no\x18\x02 \x01(\tR\tcabinetNo\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1f\n" +
	"\vtotal_slots\x18\x04 \x01(\x05R\n" +
	"totalSlots\x12'\n" +
	"\x0favailable_slots\x18\x05 \x01(\x05R\x0eavailableSlots\x12%\n" +
	"\x0eoccupied_slots\x18\x06 \x01(\x05R\roccupiedSlots\x12(\n" +
	"\x05slots\x18\a \x03(\v2\x12.order.v1.SlotInfoR\x05slots\"\xce\x01\n" +
	"\bSlotInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aslot_no\x18\x02 \x01(\tR\x06slotNo\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\"\n" +
	"\rpower_bank_id\x18\x04 \x01(\x03R\vpowerBankId\x12\"\n" +
	"\rpower_bank_no\x18\x05 \x01(\tR\vpowerBankNo\x12#\n" +
	"\rbattery_level\x18\x06 \x01(\x05R\fbatteryLevel\x12\x14\n" +
	"\x05power\x18\a \x01(\tR\x05power\"K\n" +
	"\x16GetCabinetListResponse\x121\n" +
	"\bcabinets\x18\x01 \x03(\v2\x15.order.v1.CabinetInfoR\bcabinets\"T\n" +
	"\x12GetDelayFeeRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12#\n" +
	"\rextra_minutes\x18\x02 \x01(\x05R\fextraMinutes\"\x90\x02\n" +
	"\x13GetDelayFeeResponse\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12#\n" +
	"\rextra_minutes\x18\x02 \x01(\x05R\fextraMinutes\x12%\n" +
	"\x0eadditional_fee\x18\x03 \x01(\x03R\radditionalFee\x12'\n" +
	"\x0festimated_total\x18\x04 \x01(\x03R\x0eestimatedTotal\x12-\n" +
	"\x12additional_deposit\x18\x05 \x01(\x03R\x11additionalDeposit\x12\x1d\n" +
	"\n" +
	"hourly_fee\x18\x06 \x01(\x03R\thourlyFee\x12\x1b\n" +
	"\tdaily_cap\x18\a \x01(\x03R\bdailyCap2\xe0\r\n" +
	"\x05Order\x12w\n" +
	"\x0ePreCheckBorrow\x12\x1f.order.v1.PreCheckBorrowRequest\x1a .order.v1.PreCheckBorrowResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/order/pre-check\x12k\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x1d.order.v1.CreateOrderResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/order/create\x12k\n" +
	"\vCancelOrder\x12\x1c.order.v1.CancelOrderRequest\x1a\x1d.order.v1.CancelOrderResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/order/cancel\x12w\n" +
	"\x0fReturnPowerBank\x12 .order.v1.ReturnPowerBankRequest\x1a!.order.v1.ReturnPowerBankResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/order/return\x12n\n" +
	"\fExtendRental\x12\x1d.order.v1.ExtendRentalRequest\x1a\x1e.order.v1.ExtendRentalResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/order/extend\x12u\n" +
	"\x0fGetCurrentOrder\x12 .order.v1.GetCurrentOrderRequest\x1a!.order.v1.GetCurrentOrderResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/order/current\x12n\n" +
	"\x0eGetRealTimeFee\x12\x1f.order.v1.GetRealTimeFeeRequest\x1a .order.v1.GetRealTimeFeeResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/order/fee\x12c\n" +
	"\n" +
	"ListOrders\x12\x1b.order.v1.ListOrdersRequest\x1a\x1c.order.v1.ListOrdersResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/order/list\x12\x9b\x01\n" +
	"\x19CreateCompensationPayment\x12*.order.v1.CreateCompensationPaymentRequest\x1a+.order.v1.CreateCompensationPaymentResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/order/compensation\x12e\n" +
	"\n" +
	"GetStation\x12\x1b.order.v1.GetStationRequest\x1a\x1c.order.v1.GetStationResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/station/{id}\x12\x7f\n" +
	"\x12ListNearbyStations\x12#.order.v1.ListNearbyStationsRequest\x1a$.order.v1.ListNearbyStationsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/station/nearby\x12y\n" +
	"\x0eGetCabinetList\x12\x1f.order.v1.GetCabinetListRequest\x1a .order.v1.GetCabinetListResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/station/cabinet-list\x12q\n" +
	"\x0eGetOrderDetail\x12\x1f.order.v1.GetOrderDetailRequest\x1a .order.v1.GetOrderDetailResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/order/detail\x12n\n" +
	"\vGetDelayFee\x12\x1c.order.v1.GetDelayFeeRequest\x1a\x1d.order.v1.GetDelayFeeResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/order/delay-fee\x12k\n" +
	"\vScanCabinet\x12\x1c.order.v1.ScanCabinetRequest\x1a\x1d.order.v1.ScanCabinetResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/cabinet/scanB)\n" +
	"\fapi.order.v1P\x01Z\x17monster/api/order/v1;v1b\x06proto3"

var (
	file_order_v1_order_proto_rawDescOnce sync.Once
	file_order_v1_order_proto_rawDescData []byte
)

func file_order_v1_order_proto_rawDescGZIP() []byte {
	file_order_v1_order_proto_rawDescOnce.Do(func() {
		file_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)))
	})
	return file_order_v1_order_proto_rawDescData
}

var file_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_order_v1_order_proto_goTypes = []any{
	(*PreCheckBorrowRequest)(nil),             // 0: order.v1.PreCheckBorrowRequest
	(*PreCheckBorrowResponse)(nil),            // 1: order.v1.PreCheckBorrowResponse
	(*CreateOrderRequest)(nil),                // 2: order.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),               // 3: order.v1.CreateOrderResponse
	(*CancelOrderRequest)(nil),                // 4: order.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),               // 5: order.v1.CancelOrderResponse
	(*ReturnPowerBankRequest)(nil),            // 6: order.v1.ReturnPowerBankRequest
	(*ReturnPowerBankResponse)(nil),           // 7: order.v1.ReturnPowerBankResponse
	(*ExtendRentalRequest)(nil),               // 8: order.v1.ExtendRentalRequest
	(*ExtendRentalResponse)(nil),              // 9: order.v1.ExtendRentalResponse
	(*GetCurrentOrderRequest)(nil),            // 10: order.v1.GetCurrentOrderRequest
	(*GetCurrentOrderResponse)(nil),           // 11: order.v1.GetCurrentOrderResponse
	(*GetRealTimeFeeRequest)(nil),             // 12: order.v1.GetRealTimeFeeRequest
	(*GetRealTimeFeeResponse)(nil),            // 13: order.v1.GetRealTimeFeeResponse
	(*ListOrdersRequest)(nil),                 // 14: order.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),                // 15: order.v1.ListOrdersResponse
	(*CreateCompensationPaymentRequest)(nil),  // 16: order.v1.CreateCompensationPaymentRequest
	(*CreateCompensationPaymentResponse)(nil), // 17: order.v1.CreateCompensationPaymentResponse
	(*GetStationRequest)(nil),                 // 18: order.v1.GetStationRequest
	(*GetStationResponse)(nil),                // 19: order.v1.GetStationResponse
	(*ListNearbyStationsRequest)(nil),         // 20: order.v1.ListNearbyStationsRequest
	(*ListNearbyStationsResponse)(nil),        // 21: order.v1.ListNearbyStationsResponse
	(*StationInfo)(nil),                       // 22: order.v1.StationInfo
	(*ScanCabinetRequest)(nil),                // 23: order.v1.ScanCabinetRequest
	(*ScanCabinetResponse)(nil),               // 24: order.v1.ScanCabinetResponse
	(*OrderInfo)(nil),                         // 25: order.v1.OrderInfo
	(*GetOrderDetailRequest)(nil),             // 26: order.v1.GetOrderDetailRequest
	(*OrderDetail)(nil),                       // 27: order.v1.OrderDetail
	(*GetOrderDetailResponse)(nil),            // 28: order.v1.GetOrderDetailResponse
	(*GetCabinetListRequest)(nil),             // 29: order.v1.GetCabinetListRequest
	(*CabinetInfo)(nil),                       // 30: order.v1.CabinetInfo
	(*SlotInfo)(nil),                          // 31: order.v1.SlotInfo
	(*GetCabinetListResponse)(nil),            // 32: order.v1.GetCabinetListResponse
	(*GetDelayFeeRequest)(nil),                // 33: order.v1.GetDelayFeeRequest
	(*GetDelayFeeResponse)(nil),               // 34: order.v1.GetDelayFeeResponse
}
var file_order_v1_order_proto_depIdxs = []int32{
	25, // 0: order.v1.GetCurrentOrderResponse.order:type_name -> order.v1.OrderInfo
	25, // 1: order.v1.ListOrdersResponse.list:type_name -> order.v1.OrderInfo
	22, // 2: order.v1.GetStationResponse.station:type_name -> order.v1.StationInfo
	22, // 3: order.v1.ListNearbyStationsResponse.list:type_name -> order.v1.StationInfo
	27, // 4: order.v1.GetOrderDetailResponse.order:type_name -> order.v1.OrderDetail
	31, // 5: order.v1.CabinetInfo.slots:type_name -> order.v1.SlotInfo
	30, // 6: order.v1.GetCabinetListResponse.cabinets:type_name -> order.v1.CabinetInfo
	0,  // 7: order.v1.Order.PreCheckBorrow:input_type -> order.v1.PreCheckBorrowRequest
	2,  // 8: order.v1.Order.CreateOrder:input_type -> order.v1.CreateOrderRequest
	4,  // 9: order.v1.Order.CancelOrder:input_type -> order.v1.CancelOrderRequest
	6,  // 10: order.v1.Order.ReturnPowerBank:input_type -> order.v1.ReturnPowerBankRequest
	8,  // 11: order.v1.Order.ExtendRental:input_type -> order.v1.ExtendRentalRequest
	10, // 12: order.v1.Order.GetCurrentOrder:input_type -> order.v1.GetCurrentOrderRequest
	12, // 13: order.v1.Order.GetRealTimeFee:input_type -> order.v1.GetRealTimeFeeRequest
	14, // 14: order.v1.Order.ListOrders:input_type -> order.v1.ListOrdersRequest
	16, // 15: order.v1.Order.CreateCompensationPayment:input_type -> order.v1.CreateCompensationPaymentRequest
	18, // 16: order.v1.Order.GetStation:input_type -> order.v1.GetStationRequest
	20, // 17: order.v1.Order.ListNearbyStations:input_type -> order.v1.ListNearbyStationsRequest
	29, // 18: order.v1.Order.GetCabinetList:input_type -> order.v1.GetCabinetListRequest
	26, // 19: order.v1.Order.GetOrderDetail:input_type -> order.v1.GetOrderDetailRequest
	33, // 20: order.v1.Order.GetDelayFee:input_type -> order.v1.GetDelayFeeRequest
	23, // 21: order.v1.Order.ScanCabinet:input_type -> order.v1.ScanCabinetRequest
	1,  // 22: order.v1.Order.PreCheckBorrow:output_type -> order.v1.PreCheckBorrowResponse
	3,  // 23: order.v1.Order.CreateOrder:output_type -> order.v1.CreateOrderResponse
	5,  // 24: order.v1.Order.CancelOrder:output_type -> order.v1.CancelOrderResponse
	7,  // 25: order.v1.Order.ReturnPowerBank:output_type -> order.v1.ReturnPowerBankResponse
	9,  // 26: order.v1.Order.ExtendRental:output_type -> order.v1.ExtendRentalResponse
	11, // 27: order.v1.Order.GetCurrentOrder:output_type -> order.v1.GetCurrentOrderResponse
	13, // 28: order.v1.Order.GetRealTimeFee:output_type -> order.v1.GetRealTimeFeeResponse
	15, // 29: order.v1.Order.ListOrders:output_type -> order.v1.ListOrdersResponse
	17, // 30: order.v1.Order.CreateCompensationPayment:output_type -> order.v1.CreateCompensationPaymentResponse
	19, // 31: order.v1.Order.GetStation:output_type -> order.v1.GetStationResponse
	21, // 32: order.v1.Order.ListNearbyStations:output_type -> order.v1.ListNearbyStationsResponse
	32, // 33: order.v1.Order.GetCabinetList:output_type -> order.v1.GetCabinetListResponse
	28, // 34: order.v1.Order.GetOrderDetail:output_type -> order.v1.GetOrderDetailResponse
	34, // 35: order.v1.Order.GetDelayFee:output_type -> order.v1.GetDelayFeeResponse
	24, // 36: order.v1.Order.ScanCabinet:output_type -> order.v1.ScanCabinetResponse
	22, // [22:37] is the sub-list for method output_type
	7,  // [7:22] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_order_v1_order_proto_init() }
func file_order_v1_order_proto_init() {
	if File_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_order_proto_goTypes,
		DependencyIndexes: file_order_v1_order_proto_depIdxs,
		MessageInfos:      file_order_v1_order_proto_msgTypes,
	}.Build()
	File_order_v1_order_proto = out.File
	file_order_v1_order_proto_goTypes = nil
	file_order_v1_order_proto_depIdxs = nil
}
