// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: order/v1/order.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOrderListReturnCabinets = "/order.v1.Order/ListReturnCabinets"
const OperationOrderSearchCabinet = "/order.v1.Order/SearchCabinet"

const OperationOrderCancelOrder = "/order.v1.Order/CancelOrder"
const OperationOrderCreateCompensationPayment = "/order.v1.Order/CreateCompensationPayment"
const OperationOrderCreateOrder = "/order.v1.Order/CreateOrder"
const OperationOrderExtendRental = "/order.v1.Order/ExtendRental"
const OperationOrderGetCabinetList = "/order.v1.Order/GetCabinetList"
const OperationOrderGetCurrentOrder = "/order.v1.Order/GetCurrentOrder"
const OperationOrderGetDelayFee = "/order.v1.Order/GetDelayFee"
const OperationOrderGetOrderDetail = "/order.v1.Order/GetOrderDetail"
const OperationOrderGetRealTimeFee = "/order.v1.Order/GetRealTimeFee"
const OperationOrderGetStation = "/order.v1.Order/GetStation"
const OperationOrderListNearbyStations = "/order.v1.Order/ListNearbyStations"
const OperationOrderListOrders = "/order.v1.Order/ListOrders"
const OperationOrderPreCheckBorrow = "/order.v1.Order/PreCheckBorrow"
const OperationOrderReturnPowerBank = "/order.v1.Order/ReturnPowerBank"
const OperationOrderScanCabinet = "/order.v1.Order/ScanCabinet"

type OrderHTTPServer interface {
	// CancelOrder 取消订单
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	// CreateCompensationPayment 待赔付支付入口
	CreateCompensationPayment(context.Context, *CreateCompensationPaymentRequest) (*CreateCompensationPaymentResponse, error)
	// CreateOrder 创建租借订单
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	// ExtendRental 延长租借
	ExtendRental(context.Context, *ExtendRentalRequest) (*ExtendRentalResponse, error)
	// GetCabinetList 查询站点下所有机柜及仓位详情
	GetCabinetList(context.Context, *GetCabinetListRequest) (*GetCabinetListResponse, error)
	// GetCurrentOrder 查询当前订单
	GetCurrentOrder(context.Context, *GetCurrentOrderRequest) (*GetCurrentOrderResponse, error)
	// GetDelayFee 延长租借费用预览
	GetDelayFee(context.Context, *GetDelayFeeRequest) (*GetDelayFeeResponse, error)
	// GetOrderDetail 查询订单详情（含借还机柜仓位信息）
	GetOrderDetail(context.Context, *GetOrderDetailRequest) (*GetOrderDetailResponse, error)
	// GetRealTimeFee 实时费用查询
	GetRealTimeFee(context.Context, *GetRealTimeFeeRequest) (*GetRealTimeFeeResponse, error)
	// GetStation 获取站点详情
	GetStation(context.Context, *GetStationRequest) (*GetStationResponse, error)
	// ListReturnCabinets 查询附近可归还机柜（含空仓位数量和距离）
	ListReturnCabinets(context.Context, *ListReturnCabinetsRequest) (*ListReturnCabinetsResponse, error)
	// SearchCabinet 根据机柜编号搜索机柜
	SearchCabinet(context.Context, *SearchCabinetRequest) (*SearchCabinetResponse, error)
	// ListNearbyStations 查询附近站点（含距离和空闲充电宝数）
	ListNearbyStations(context.Context, *ListNearbyStationsRequest) (*ListNearbyStationsResponse, error)
	// ListOrders 历史订单查询
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
	// PreCheckBorrow 租借前预检
	PreCheckBorrow(context.Context, *PreCheckBorrowRequest) (*PreCheckBorrowResponse, error)
	// ReturnPowerBank 归还充电宝
	ReturnPowerBank(context.Context, *ReturnPowerBankRequest) (*ReturnPowerBankResponse, error)
	// ScanCabinet 扫码解析机柜（扫描二维码进入机柜详情）
	ScanCabinet(context.Context, *ScanCabinetRequest) (*ScanCabinetResponse, error)
}

func RegisterOrderHTTPServer(s *http.Server, srv OrderHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/order/pre-check", _Order_PreCheckBorrow0_HTTP_Handler(srv))
	r.POST("/api/v1/order/create", _Order_CreateOrder0_HTTP_Handler(srv))
	r.POST("/api/v1/order/cancel", _Order_CancelOrder0_HTTP_Handler(srv))
	r.POST("/api/v1/order/return", _Order_ReturnPowerBank0_HTTP_Handler(srv))
	r.POST("/api/v1/order/extend", _Order_ExtendRental0_HTTP_Handler(srv))
	r.GET("/api/v1/order/current", _Order_GetCurrentOrder0_HTTP_Handler(srv))
	r.GET("/api/v1/order/fee", _Order_GetRealTimeFee0_HTTP_Handler(srv))
	r.GET("/api/v1/order/list", _Order_ListOrders0_HTTP_Handler(srv))
	r.POST("/api/v1/order/compensation", _Order_CreateCompensationPayment0_HTTP_Handler(srv))
	r.GET("/api/v1/station/nearby", _Order_ListNearbyStations0_HTTP_Handler(srv))
	r.GET("/api/v1/station/cabinet-list", _Order_GetCabinetList0_HTTP_Handler(srv))
	r.GET("/api/v1/cabinet/return-list", _Order_ListReturnCabinets0_HTTP_Handler(srv))
	r.GET("/api/v1/cabinet/search", _Order_SearchCabinet0_HTTP_Handler(srv))
	r.GET("/api/v1/station/{id}", _Order_GetStation0_HTTP_Handler(srv))
	r.GET("/api/v1/order/detail", _Order_GetOrderDetail0_HTTP_Handler(srv))
	r.POST("/api/v1/order/delay-fee", _Order_GetDelayFee0_HTTP_Handler(srv))
	r.POST("/api/v1/cabinet/scan", _Order_ScanCabinet0_HTTP_Handler(srv))
}

func _Order_PreCheckBorrow0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PreCheckBorrowRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderPreCheckBorrow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PreCheckBorrow(ctx, req.(*PreCheckBorrowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PreCheckBorrowResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_CreateOrder0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderCreateOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateOrder(ctx, req.(*CreateOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateOrderResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_CancelOrder0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderCancelOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelOrder(ctx, req.(*CancelOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CancelOrderResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_ReturnPowerBank0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReturnPowerBankRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderReturnPowerBank)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReturnPowerBank(ctx, req.(*ReturnPowerBankRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReturnPowerBankResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_ExtendRental0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExtendRentalRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderExtendRental)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExtendRental(ctx, req.(*ExtendRentalRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExtendRentalResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_GetCurrentOrder0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCurrentOrderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderGetCurrentOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCurrentOrder(ctx, req.(*GetCurrentOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCurrentOrderResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_GetRealTimeFee0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRealTimeFeeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderGetRealTimeFee)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRealTimeFee(ctx, req.(*GetRealTimeFeeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRealTimeFeeResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_ListOrders0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderListOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOrders(ctx, req.(*ListOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListOrdersResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_CreateCompensationPayment0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCompensationPaymentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderCreateCompensationPayment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCompensationPayment(ctx, req.(*CreateCompensationPaymentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateCompensationPaymentResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_GetStation0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderGetStation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStation(ctx, req.(*GetStationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetStationResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_ListNearbyStations0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNearbyStationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderListNearbyStations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNearbyStations(ctx, req.(*ListNearbyStationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListNearbyStationsResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_GetCabinetList0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCabinetListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderGetCabinetList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCabinetList(ctx, req.(*GetCabinetListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCabinetListResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_GetOrderDetail0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderGetOrderDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrderDetail(ctx, req.(*GetOrderDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOrderDetailResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_GetDelayFee0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDelayFeeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderGetDelayFee)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDelayFee(ctx, req.(*GetDelayFeeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDelayFeeResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_ScanCabinet0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ScanCabinetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderScanCabinet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ScanCabinet(ctx, req.(*ScanCabinetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ScanCabinetResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_ListReturnCabinets0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListReturnCabinetsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderListReturnCabinets)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListReturnCabinets(ctx, req.(*ListReturnCabinetsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListReturnCabinetsResponse)
		return ctx.Result(200, reply)
	}
}

func _Order_SearchCabinet0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchCabinetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderSearchCabinet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchCabinet(ctx, req.(*SearchCabinetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchCabinetResponse)
		return ctx.Result(200, reply)
	}
}

type OrderHTTPClient interface {
	// CancelOrder 取消订单
	CancelOrder(ctx context.Context, req *CancelOrderRequest, opts ...http.CallOption) (rsp *CancelOrderResponse, err error)
	// CreateCompensationPayment 待赔付支付入口
	CreateCompensationPayment(ctx context.Context, req *CreateCompensationPaymentRequest, opts ...http.CallOption) (rsp *CreateCompensationPaymentResponse, err error)
	// CreateOrder 创建租借订单
	CreateOrder(ctx context.Context, req *CreateOrderRequest, opts ...http.CallOption) (rsp *CreateOrderResponse, err error)
	// ExtendRental 延长租借
	ExtendRental(ctx context.Context, req *ExtendRentalRequest, opts ...http.CallOption) (rsp *ExtendRentalResponse, err error)
	// GetCabinetList 查询站点下所有机柜及仓位详情
	GetCabinetList(ctx context.Context, req *GetCabinetListRequest, opts ...http.CallOption) (rsp *GetCabinetListResponse, err error)
	// GetCurrentOrder 查询当前订单
	GetCurrentOrder(ctx context.Context, req *GetCurrentOrderRequest, opts ...http.CallOption) (rsp *GetCurrentOrderResponse, err error)
	// GetDelayFee 延长租借费用预览
	GetDelayFee(ctx context.Context, req *GetDelayFeeRequest, opts ...http.CallOption) (rsp *GetDelayFeeResponse, err error)
	// GetOrderDetail 查询订单详情（含借还机柜仓位信息）
	GetOrderDetail(ctx context.Context, req *GetOrderDetailRequest, opts ...http.CallOption) (rsp *GetOrderDetailResponse, err error)
	// GetRealTimeFee 实时费用查询
	GetRealTimeFee(ctx context.Context, req *GetRealTimeFeeRequest, opts ...http.CallOption) (rsp *GetRealTimeFeeResponse, err error)
	// GetStation 获取站点详情
	GetStation(ctx context.Context, req *GetStationRequest, opts ...http.CallOption) (rsp *GetStationResponse, err error)
	// ListNearbyStations 查询附近站点（含距离和空闲充电宝数）
	ListNearbyStations(ctx context.Context, req *ListNearbyStationsRequest, opts ...http.CallOption) (rsp *ListNearbyStationsResponse, err error)
	ListReturnCabinets(ctx context.Context, req *ListReturnCabinetsRequest, opts ...http.CallOption) (rsp *ListReturnCabinetsResponse, err error)
	SearchCabinet(ctx context.Context, req *SearchCabinetRequest, opts ...http.CallOption) (rsp *SearchCabinetResponse, err error)
	// ListOrders 历史订单查询
	ListOrders(ctx context.Context, req *ListOrdersRequest, opts ...http.CallOption) (rsp *ListOrdersResponse, err error)
	// PreCheckBorrow 租借前预检
	PreCheckBorrow(ctx context.Context, req *PreCheckBorrowRequest, opts ...http.CallOption) (rsp *PreCheckBorrowResponse, err error)
	// ReturnPowerBank 归还充电宝
	ReturnPowerBank(ctx context.Context, req *ReturnPowerBankRequest, opts ...http.CallOption) (rsp *ReturnPowerBankResponse, err error)
	// ScanCabinet 扫码解析机柜（扫描二维码进入机柜详情）
	ScanCabinet(ctx context.Context, req *ScanCabinetRequest, opts ...http.CallOption) (rsp *ScanCabinetResponse, err error)
}

type OrderHTTPClientImpl struct {
	cc *http.Client
}

func NewOrderHTTPClient(client *http.Client) OrderHTTPClient {
	return &OrderHTTPClientImpl{client}
}

// CancelOrder 取消订单
func (c *OrderHTTPClientImpl) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...http.CallOption) (*CancelOrderResponse, error) {
	var out CancelOrderResponse
	pattern := "/api/v1/order/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderCancelOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateCompensationPayment 待赔付支付入口
func (c *OrderHTTPClientImpl) CreateCompensationPayment(ctx context.Context, in *CreateCompensationPaymentRequest, opts ...http.CallOption) (*CreateCompensationPaymentResponse, error) {
	var out CreateCompensationPaymentResponse
	pattern := "/api/v1/order/compensation"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderCreateCompensationPayment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateOrder 创建租借订单
func (c *OrderHTTPClientImpl) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...http.CallOption) (*CreateOrderResponse, error) {
	var out CreateOrderResponse
	pattern := "/api/v1/order/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderCreateOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ExtendRental 延长租借
func (c *OrderHTTPClientImpl) ExtendRental(ctx context.Context, in *ExtendRentalRequest, opts ...http.CallOption) (*ExtendRentalResponse, error) {
	var out ExtendRentalResponse
	pattern := "/api/v1/order/extend"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderExtendRental))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCabinetList 查询站点下所有机柜及仓位详情
func (c *OrderHTTPClientImpl) GetCabinetList(ctx context.Context, in *GetCabinetListRequest, opts ...http.CallOption) (*GetCabinetListResponse, error) {
	var out GetCabinetListResponse
	pattern := "/api/v1/station/cabinet-list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderGetCabinetList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCurrentOrder 查询当前订单
func (c *OrderHTTPClientImpl) GetCurrentOrder(ctx context.Context, in *GetCurrentOrderRequest, opts ...http.CallOption) (*GetCurrentOrderResponse, error) {
	var out GetCurrentOrderResponse
	pattern := "/api/v1/order/current"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderGetCurrentOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDelayFee 延长租借费用预览
func (c *OrderHTTPClientImpl) GetDelayFee(ctx context.Context, in *GetDelayFeeRequest, opts ...http.CallOption) (*GetDelayFeeResponse, error) {
	var out GetDelayFeeResponse
	pattern := "/api/v1/order/delay-fee"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderGetDelayFee))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetOrderDetail 查询订单详情（含借还机柜仓位信息）
func (c *OrderHTTPClientImpl) GetOrderDetail(ctx context.Context, in *GetOrderDetailRequest, opts ...http.CallOption) (*GetOrderDetailResponse, error) {
	var out GetOrderDetailResponse
	pattern := "/api/v1/order/detail"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderGetOrderDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRealTimeFee 实时费用查询
func (c *OrderHTTPClientImpl) GetRealTimeFee(ctx context.Context, in *GetRealTimeFeeRequest, opts ...http.CallOption) (*GetRealTimeFeeResponse, error) {
	var out GetRealTimeFeeResponse
	pattern := "/api/v1/order/fee"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderGetRealTimeFee))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStation 获取站点详情
func (c *OrderHTTPClientImpl) GetStation(ctx context.Context, in *GetStationRequest, opts ...http.CallOption) (*GetStationResponse, error) {
	var out GetStationResponse
	pattern := "/api/v1/station/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderGetStation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListNearbyStations 查询附近站点（含距离和空闲充电宝数）
func (c *OrderHTTPClientImpl) ListNearbyStations(ctx context.Context, in *ListNearbyStationsRequest, opts ...http.CallOption) (*ListNearbyStationsResponse, error) {
	var out ListNearbyStationsResponse
	pattern := "/api/v1/station/nearby"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderListNearbyStations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListOrders 历史订单查询
func (c *OrderHTTPClientImpl) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...http.CallOption) (*ListOrdersResponse, error) {
	var out ListOrdersResponse
	pattern := "/api/v1/order/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderListOrders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PreCheckBorrow 租借前预检
func (c *OrderHTTPClientImpl) PreCheckBorrow(ctx context.Context, in *PreCheckBorrowRequest, opts ...http.CallOption) (*PreCheckBorrowResponse, error) {
	var out PreCheckBorrowResponse
	pattern := "/api/v1/order/pre-check"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderPreCheckBorrow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ReturnPowerBank 归还充电宝
func (c *OrderHTTPClientImpl) ReturnPowerBank(ctx context.Context, in *ReturnPowerBankRequest, opts ...http.CallOption) (*ReturnPowerBankResponse, error) {
	var out ReturnPowerBankResponse
	pattern := "/api/v1/order/return"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderReturnPowerBank))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ScanCabinet 扫码解析机柜（扫描二维码进入机柜详情）
func (c *OrderHTTPClientImpl) ScanCabinet(ctx context.Context, in *ScanCabinetRequest, opts ...http.CallOption) (*ScanCabinetResponse, error) {
	var out ScanCabinetResponse
	pattern := "/api/v1/cabinet/scan"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderScanCabinet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderHTTPClientImpl) ListReturnCabinets(ctx context.Context, in *ListReturnCabinetsRequest, opts ...http.CallOption) (*ListReturnCabinetsResponse, error) {
	var out ListReturnCabinetsResponse
	pattern := "/api/v1/cabinet/return-list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderListReturnCabinets))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderHTTPClientImpl) SearchCabinet(ctx context.Context, in *SearchCabinetRequest, opts ...http.CallOption) (*SearchCabinetResponse, error) {
	var out SearchCabinetResponse
	pattern := "/api/v1/cabinet/search"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderSearchCabinet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
