// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: user/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                // 用户ID
	OpenId        string                 `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`           // 微信open_id
	UnionId       string                 `protobuf:"bytes,3,opt,name=union_id,json=unionId,proto3" json:"union_id,omitempty"`        // 微信union_id
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`                     // 昵称
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`                         // 头像URL
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`                           // 手机号
	Gender        int32                  `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`                        // 性别：0-未知 1-男 2-女
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`                        // 状态：1-正常 2-冻结
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`  // 创建时间
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *UserInfo) GetUnionId() string {
	if x != nil {
		return x.UnionId
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`         // 微信临时登录凭证(code)
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"` // 微信昵称（首次登录时使用）
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`     // 微信头像URL（首次登录时使用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LoginRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // JWT令牌
	User          *UserInfo              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`   // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`       // 手机号
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`         // 短信验证码
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"` // 昵称（首次登录时使用）
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`     // 头像URL（首次登录时使用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginPhoneRequest) Reset() {
	*x = LoginPhoneRequest{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginPhoneRequest) ProtoMessage() {}

func (x *LoginPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginPhoneRequest.ProtoReflect.Descriptor instead.
func (*LoginPhoneRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginPhoneRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginPhoneRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LoginPhoneRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type SendSmsCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"` // 手机号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsCodeRequest) Reset() {
	*x = SendSmsCodeRequest{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsCodeRequest) ProtoMessage() {}

func (x *SendSmsCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsCodeRequest.ProtoReflect.Descriptor instead.
func (*SendSmsCodeRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *SendSmsCodeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type SendSmsCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 操作结果消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsCodeResponse) Reset() {
	*x = SendSmsCodeResponse{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsCodeResponse) ProtoMessage() {}

func (x *SendSmsCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsCodeResponse.ProtoReflect.Descriptor instead.
func (*SendSmsCodeResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *SendSmsCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BindPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"` // 手机号
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`   // 短信验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindPhoneRequest) Reset() {
	*x = BindPhoneRequest{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindPhoneRequest) ProtoMessage() {}

func (x *BindPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindPhoneRequest.ProtoReflect.Descriptor instead.
func (*BindPhoneRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *BindPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *BindPhoneRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type BindPhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 操作结果消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindPhoneResponse) Reset() {
	*x = BindPhoneResponse{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindPhoneResponse) ProtoMessage() {}

func (x *BindPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindPhoneResponse.ProtoReflect.Descriptor instead.
func (*BindPhoneResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *BindPhoneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetProfileResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"` // 昵称
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`     // 头像URL
	Gender        int32                  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`    // 性别：0-未知 1-男 2-女
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateProfileRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // 更新后的用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateProfileResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{12}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 操作结果消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *LogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WalletInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                            // 钱包ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                      // 用户ID
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`                                  // 余额（分）
	Frozen        int64                  `protobuf:"varint,4,opt,name=frozen,proto3" json:"frozen,omitempty"`                                    // 冻结金额（分）
	TotalRecharge int64                  `protobuf:"varint,5,opt,name=total_recharge,json=totalRecharge,proto3" json:"total_recharge,omitempty"` // 累计充值（分）
	TotalConsume  int64                  `protobuf:"varint,6,opt,name=total_consume,json=totalConsume,proto3" json:"total_consume,omitempty"`    // 累计消费（分）
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                                    // 状态：1-正常 2-冻结
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`              // 创建时间
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`              // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletInfo) Reset() {
	*x = WalletInfo{}
	mi := &file_user_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletInfo) ProtoMessage() {}

func (x *WalletInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletInfo.ProtoReflect.Descriptor instead.
func (*WalletInfo) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *WalletInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WalletInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WalletInfo) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *WalletInfo) GetFrozen() int64 {
	if x != nil {
		return x.Frozen
	}
	return 0
}

func (x *WalletInfo) GetTotalRecharge() int64 {
	if x != nil {
		return x.TotalRecharge
	}
	return 0
}

func (x *WalletInfo) GetTotalConsume() int64 {
	if x != nil {
		return x.TotalConsume
	}
	return 0
}

func (x *WalletInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WalletInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WalletInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TransactionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                            // 记录ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                      // 用户ID
	WalletId      int64                  `protobuf:"varint,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`                // 钱包ID
	OrderId       string                 `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                    // 关联订单号
	TradeType     string                 `protobuf:"bytes,5,opt,name=trade_type,json=tradeType,proto3" json:"trade_type,omitempty"`              // 交易类型
	Amount        int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`                                    // 交易金额（分）
	BalanceBefore int64                  `protobuf:"varint,7,opt,name=balance_before,json=balanceBefore,proto3" json:"balance_before,omitempty"` // 交易前余额（分）
	BalanceAfter  int64                  `protobuf:"varint,8,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`    // 交易后余额（分）
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`                                     // 备注
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`             // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInfo) Reset() {
	*x = TransactionInfo{}
	mi := &file_user_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfo) ProtoMessage() {}

func (x *TransactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfo.ProtoReflect.Descriptor instead.
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *TransactionInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TransactionInfo) GetWalletId() int64 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

func (x *TransactionInfo) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *TransactionInfo) GetTradeType() string {
	if x != nil {
		return x.TradeType
	}
	return ""
}

func (x *TransactionInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionInfo) GetBalanceBefore() int64 {
	if x != nil {
		return x.BalanceBefore
	}
	return 0
}

func (x *TransactionInfo) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *TransactionInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *TransactionInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_user_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{16}
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *WalletInfo            `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"` // 钱包信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_user_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetWalletResponse) GetWallet() *WalletInfo {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_user_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *ListTransactionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransactionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TransactionInfo     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`                          // 交易记录列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总记录数
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_user_v1_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{19}
}

func (x *ListTransactionsResponse) GetList() []*TransactionInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListTransactionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTransactionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransactionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PayDepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"` // 押金金额（分）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayDepositRequest) Reset() {
	*x = PayDepositRequest{}
	mi := &file_user_v1_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayDepositRequest) ProtoMessage() {}

func (x *PayDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayDepositRequest.ProtoReflect.Descriptor instead.
func (*PayDepositRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{20}
}

func (x *PayDepositRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PayDepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 操作结果消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayDepositResponse) Reset() {
	*x = PayDepositResponse{}
	mi := &file_user_v1_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayDepositResponse) ProtoMessage() {}

func (x *PayDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayDepositResponse.ProtoReflect.Descriptor instead.
func (*PayDepositResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{21}
}

func (x *PayDepositResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RechargeDepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"` // 充值金额（分）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeDepositRequest) Reset() {
	*x = RechargeDepositRequest{}
	mi := &file_user_v1_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeDepositRequest) ProtoMessage() {}

func (x *RechargeDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeDepositRequest.ProtoReflect.Descriptor instead.
func (*RechargeDepositRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{22}
}

func (x *RechargeDepositRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type RechargeDepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 操作结果消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeDepositResponse) Reset() {
	*x = RechargeDepositResponse{}
	mi := &file_user_v1_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeDepositResponse) ProtoMessage() {}

func (x *RechargeDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeDepositResponse.ProtoReflect.Descriptor instead.
func (*RechargeDepositResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{23}
}

func (x *RechargeDepositResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RefundDepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundDepositRequest) Reset() {
	*x = RefundDepositRequest{}
	mi := &file_user_v1_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundDepositRequest) ProtoMessage() {}

func (x *RefundDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundDepositRequest.ProtoReflect.Descriptor instead.
func (*RefundDepositRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{24}
}

type RefundDepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 操作结果消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundDepositResponse) Reset() {
	*x = RefundDepositResponse{}
	mi := &file_user_v1_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundDepositResponse) ProtoMessage() {}

func (x *RefundDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundDepositResponse.ProtoReflect.Descriptor instead.
func (*RefundDepositResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{25}
}

func (x *RefundDepositResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetDepositInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositInfoRequest) Reset() {
	*x = GetDepositInfoRequest{}
	mi := &file_user_v1_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositInfoRequest) ProtoMessage() {}

func (x *GetDepositInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDepositInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{26}
}

type GetDepositInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasDeposit    bool                   `protobuf:"varint,1,opt,name=has_deposit,json=hasDeposit,proto3" json:"has_deposit,omitempty"`          // 是否已缴纳押金
	DepositAmount int64                  `protobuf:"varint,2,opt,name=deposit_amount,json=depositAmount,proto3" json:"deposit_amount,omitempty"` // 押金标准金额（分）
	DepositFrozen int64                  `protobuf:"varint,3,opt,name=deposit_frozen,json=depositFrozen,proto3" json:"deposit_frozen,omitempty"` // 当前冻结押金（分）
	WalletBalance int64                  `protobuf:"varint,4,opt,name=wallet_balance,json=walletBalance,proto3" json:"wallet_balance,omitempty"` // 钱包余额（分）
	DepositEnough bool                   `protobuf:"varint,5,opt,name=deposit_enough,json=depositEnough,proto3" json:"deposit_enough,omitempty"` // 余额是否足够支付押金
	Rules         string                 `protobuf:"bytes,6,opt,name=rules,proto3" json:"rules,omitempty"`                                       // 押金规则说明
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositInfoResponse) Reset() {
	*x = GetDepositInfoResponse{}
	mi := &file_user_v1_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositInfoResponse) ProtoMessage() {}

func (x *GetDepositInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDepositInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{27}
}

func (x *GetDepositInfoResponse) GetHasDeposit() bool {
	if x != nil {
		return x.HasDeposit
	}
	return false
}

func (x *GetDepositInfoResponse) GetDepositAmount() int64 {
	if x != nil {
		return x.DepositAmount
	}
	return 0
}

func (x *GetDepositInfoResponse) GetDepositFrozen() int64 {
	if x != nil {
		return x.DepositFrozen
	}
	return 0
}

func (x *GetDepositInfoResponse) GetWalletBalance() int64 {
	if x != nil {
		return x.WalletBalance
	}
	return 0
}

func (x *GetDepositInfoResponse) GetDepositEnough() bool {
	if x != nil {
		return x.DepositEnough
	}
	return false
}

func (x *GetDepositInfoResponse) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\auser.v1\x1a\x1cgoogle/api/annotations.proto\"\x86\x02\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aopen_id\x18\x02 \x01(\tR\x06openId\x12\x19\n" +
	"\bunion_id\x18\x03 \x01(\tR\aunionId\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x16\n" +
	"\x06gender\x18\a \x01(\x05R\x06gender\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"V\n" +
	"\fLoginRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"L\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12%\n" +
	"\x04user\x18\x02 \x01(\v2\x11.user.v1.UserInfoR\x04user\"q\n" +
	"\x11LoginPhoneRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"*\n" +
	"\x12SendSmsCodeRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"/\n" +
	"\x13SendSmsCodeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"<\n" +
	"\x10BindPhoneRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"-\n" +
	"\x11BindPhoneResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x13\n" +
	"\x11GetProfileRequest\";\n" +
	"\x12GetProfileResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.user.v1.UserInfoR\x04user\"b\n" +
	"\x14UpdateProfileRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x05R\x06gender\">\n" +
	"\x15UpdateProfileResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.user.v1.UserInfoR\x04user\"\x0f\n" +
	"\rLogoutRequest\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x89\x02\n" +
	"\n" +
	"WalletInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12\x16\n" +
	"\x06frozen\x18\x04 \x01(\x03R\x06frozen\x12%\n" +
	"\x0etotal_recharge\x18\x05 \x01(\x03R\rtotalRecharge\x12#\n" +
	"\rtotal_consume\x18\x06 \x01(\x03R\ftotalConsume\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xac\x02\n" +
	"\x0fTransactionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x03 \x01(\x03R\bwalletId\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"trade_type\x18\x05 \x01(\tR\ttradeType\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12%\n" +
	"\x0ebalance_before\x18\a \x01(\x03R\rbalanceBefore\x12#\n" +
	"\rbalance_after\x18\b \x01(\x03R\fbalanceAfter\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"\x12\n" +
	"\x10GetWalletRequest\"@\n" +
	"\x11GetWalletResponse\x12+\n" +
	"\x06wallet\x18\x01 \x01(\v2\x13.user.v1.WalletInfoR\x06wallet\"J\n" +
	"\x17ListTransactionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x8f\x01\n" +
	"\x18ListTransactionsResponse\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.user.v1.TransactionInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"+\n" +
	"\x11PayDepositRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\".\n" +
	"\x12PayDepositResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"0\n" +
	"\x16RechargeDepositRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\"3\n" +
	"\x17RechargeDepositResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x16\n" +
	"\x14RefundDepositRequest\"1\n" +
	"\x15RefundDepositResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x17\n" +
	"\x15GetDepositInfoRequest\"\xeb\x01\n" +
	"\x16GetDepositInfoResponse\x12\x1f\n" +
	"\vhas_deposit\x18\x01 \x01(\bR\n" +
	"hasDeposit\x12%\n" +
	"\x0edeposit_amount\x18\x02 \x01(\x03R\rdepositAmount\x12%\n" +
	"\x0edeposit_frozen\x18\x03 \x01(\x03R\rdepositFrozen\x12%\n" +
	"\x0ewallet_balance\x18\x04 \x01(\x03R\rwalletBalance\x12%\n" +
	"\x0edeposit_enough\x18\x05 \x01(\bR\rdepositEnough\x12\x14\n" +
	"\x05rules\x18\x06 \x01(\tR\x05rules2\x8b\v\n" +
	"\x04User\x12U\n" +
	"\x05Login\x12\x15.user.v1.LoginRequest\x1a\x16.user.v1.LoginResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/user/login\x12e\n" +
	"\n" +
	"LoginPhone\x12\x1a.user.v1.LoginPhoneRequest\x1a\x16.user.v1.LoginResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/user/login-phone\x12o\n" +
	"\vSendSmsCode\x12\x1b.user.v1.SendSmsCodeRequest\x1a\x1c.user.v1.SendSmsCodeResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/user/send-sms-code\x12f\n" +
	"\tBindPhone\x12\x19.user.v1.BindPhoneRequest\x1a\x1a.user.v1.BindPhoneResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/user/bind-phone\x12c\n" +
	"\n" +
	"GetProfile\x12\x1a.user.v1.GetProfileRequest\x1a\x1b.user.v1.GetProfileResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/user/profile\x12o\n" +
	"\rUpdateProfile\x12\x1d.user.v1.UpdateProfileRequest\x1a\x1e.user.v1.UpdateProfileResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/api/v1/user/profile\x12Y\n" +
	"\x06Logout\x12\x16.user.v1.LogoutRequest\x1a\x17.user.v1.LogoutResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/user/logout\x12Z\n" +
	"\tGetWallet\x12\x19.user.v1.GetWalletRequest\x1a\x1a.user.v1.GetWalletResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/wallet\x12|\n" +
	"\x10ListTransactions\x12 .user.v1.ListTransactionsRequest\x1a!.user.v1.ListTransactionsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/wallet/transactions\x12l\n" +
	"\n" +
	"PayDeposit\x12\x1a.user.v1.PayDepositRequest\x1a\x1b.user.v1.PayDepositResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/wallet/deposit/pay\x12\x80\x01\n" +
	"\x0fRechargeDeposit\x12\x1f.user.v1.RechargeDepositRequest\x1a .user.v1.RechargeDepositResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/wallet/deposit/recharge\x12x\n" +
	"\rRefundDeposit\x12\x1d.user.v1.RefundDepositRequest\x1a\x1e.user.v1.RefundDepositResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/wallet/deposit/refund\x12v\n" +
	"\x0eGetDepositInfo\x12\x1e.user.v1.GetDepositInfoRequest\x1a\x1f.user.v1.GetDepositInfoResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/wallet/deposit-infoB'\n" +
	"\vapi.user.v1P\x01Z\x16monster/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_user_v1_user_proto_goTypes = []any{
	(*UserInfo)(nil),                 // 0: user.v1.UserInfo
	(*LoginRequest)(nil),             // 1: user.v1.LoginRequest
	(*LoginResponse)(nil),            // 2: user.v1.LoginResponse
	(*LoginPhoneRequest)(nil),        // 3: user.v1.LoginPhoneRequest
	(*SendSmsCodeRequest)(nil),       // 4: user.v1.SendSmsCodeRequest
	(*SendSmsCodeResponse)(nil),      // 5: user.v1.SendSmsCodeResponse
	(*BindPhoneRequest)(nil),         // 6: user.v1.BindPhoneRequest
	(*BindPhoneResponse)(nil),        // 7: user.v1.BindPhoneResponse
	(*GetProfileRequest)(nil),        // 8: user.v1.GetProfileRequest
	(*GetProfileResponse)(nil),       // 9: user.v1.GetProfileResponse
	(*UpdateProfileRequest)(nil),     // 10: user.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),    // 11: user.v1.UpdateProfileResponse
	(*LogoutRequest)(nil),            // 12: user.v1.LogoutRequest
	(*LogoutResponse)(nil),           // 13: user.v1.LogoutResponse
	(*WalletInfo)(nil),               // 14: user.v1.WalletInfo
	(*TransactionInfo)(nil),          // 15: user.v1.TransactionInfo
	(*GetWalletRequest)(nil),         // 16: user.v1.GetWalletRequest
	(*GetWalletResponse)(nil),        // 17: user.v1.GetWalletResponse
	(*ListTransactionsRequest)(nil),  // 18: user.v1.ListTransactionsRequest
	(*ListTransactionsResponse)(nil), // 19: user.v1.ListTransactionsResponse
	(*PayDepositRequest)(nil),        // 20: user.v1.PayDepositRequest
	(*PayDepositResponse)(nil),       // 21: user.v1.PayDepositResponse
	(*RechargeDepositRequest)(nil),   // 22: user.v1.RechargeDepositRequest
	(*RechargeDepositResponse)(nil),  // 23: user.v1.RechargeDepositResponse
	(*RefundDepositRequest)(nil),     // 24: user.v1.RefundDepositRequest
	(*RefundDepositResponse)(nil),    // 25: user.v1.RefundDepositResponse
	(*GetDepositInfoRequest)(nil),    // 26: user.v1.GetDepositInfoRequest
	(*GetDepositInfoResponse)(nil),   // 27: user.v1.GetDepositInfoResponse
}
var file_user_v1_user_proto_depIdxs = []int32{
	0,  // 0: user.v1.LoginResponse.user:type_name -> user.v1.UserInfo
	0,  // 1: user.v1.GetProfileResponse.user:type_name -> user.v1.UserInfo
	0,  // 2: user.v1.UpdateProfileResponse.user:type_name -> user.v1.UserInfo
	14, // 3: user.v1.GetWalletResponse.wallet:type_name -> user.v1.WalletInfo
	15, // 4: user.v1.ListTransactionsResponse.list:type_name -> user.v1.TransactionInfo
	1,  // 5: user.v1.User.Login:input_type -> user.v1.LoginRequest
	3,  // 6: user.v1.User.LoginPhone:input_type -> user.v1.LoginPhoneRequest
	4,  // 7: user.v1.User.SendSmsCode:input_type -> user.v1.SendSmsCodeRequest
	6,  // 8: user.v1.User.BindPhone:input_type -> user.v1.BindPhoneRequest
	8,  // 9: user.v1.User.GetProfile:input_type -> user.v1.GetProfileRequest
	10, // 10: user.v1.User.UpdateProfile:input_type -> user.v1.UpdateProfileRequest
	12, // 11: user.v1.User.Logout:input_type -> user.v1.LogoutRequest
	16, // 12: user.v1.User.GetWallet:input_type -> user.v1.GetWalletRequest
	18, // 13: user.v1.User.ListTransactions:input_type -> user.v1.ListTransactionsRequest
	20, // 14: user.v1.User.PayDeposit:input_type -> user.v1.PayDepositRequest
	22, // 15: user.v1.User.RechargeDeposit:input_type -> user.v1.RechargeDepositRequest
	24, // 16: user.v1.User.RefundDeposit:input_type -> user.v1.RefundDepositRequest
	26, // 17: user.v1.User.GetDepositInfo:input_type -> user.v1.GetDepositInfoRequest
	2,  // 18: user.v1.User.Login:output_type -> user.v1.LoginResponse
	2,  // 19: user.v1.User.LoginPhone:output_type -> user.v1.LoginResponse
	5,  // 20: user.v1.User.SendSmsCode:output_type -> user.v1.SendSmsCodeResponse
	7,  // 21: user.v1.User.BindPhone:output_type -> user.v1.BindPhoneResponse
	9,  // 22: user.v1.User.GetProfile:output_type -> user.v1.GetProfileResponse
	11, // 23: user.v1.User.UpdateProfile:output_type -> user.v1.UpdateProfileResponse
	13, // 24: user.v1.User.Logout:output_type -> user.v1.LogoutResponse
	17, // 25: user.v1.User.GetWallet:output_type -> user.v1.GetWalletResponse
	19, // 26: user.v1.User.ListTransactions:output_type -> user.v1.ListTransactionsResponse
	21, // 27: user.v1.User.PayDeposit:output_type -> user.v1.PayDepositResponse
	23, // 28: user.v1.User.RechargeDeposit:output_type -> user.v1.RechargeDepositResponse
	25, // 29: user.v1.User.RefundDeposit:output_type -> user.v1.RefundDepositResponse
	27, // 30: user.v1.User.GetDepositInfo:output_type -> user.v1.GetDepositInfoResponse
	18, // [18:31] is the sub-list for method output_type
	5,  // [5:18] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
